lib/src/configuration.cc

We know ensure that the entire log directory path is created instead of
checking whether the parent dir exists.

(maint) Creaate the log directory if necessary

---

exe/main.cc
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/util/posix/daemonize.cc

Here we allow the agent to start in a unconfigured mode to help
facilitate acceptance testing.
When the key parameters like server, ca, cert and key are not set,
instead of starting normally the server will start a busy loop. At this
point the agent should still behave normally to signals.

(PCP-30) Agent should be able to start unconfigured

---

lib/inc/pxp-agent/util/posix/pid_file.hpp
lib/src/util/posix/daemonize.cc
lib/src/util/posix/pid_file.cc
lib/tests/CMakeLists.txt

Removing the file locking functionality based on flock(); temporary fix.

(PCP-49) Removing PIDFile lock functionality temporarily

---

lib/src/configuration.cc

In case no config file was specified from CL, we check if the default
one exists; in case not we set logging at debug level before starting
the agent in unconfigured mode.

(maint) Ensure logging is set in unconfigured mode

---

ext/debian/pxp-agent.default
ext/debian/pxp-agent.init
ext/osx/pxp-agent.plist
ext/redhat/pxp-agent.init
ext/redhat/pxp-agent.sysconfig
ext/solaris/smf/pxp-agent.xml
ext/suse/pxp-agent.init
ext/systemd/pxp-agent.service

This commit adds init scripts and service config
files for initialization of the PXP agent service.
These are derived as wholly as possible from the
facilities currently used for Puppet in the AIO
puppet-agent.

(CTH-390) Add PXP agent init scripts

---

exe/main.cc
lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/util/posix/pid_file.hpp
lib/src/util/posix/daemonize.cc
lib/src/util/posix/pid_file.cc
lib/tests/CMakeLists.txt
lib/tests/unit/util/posix/pid_file_test.cc

In PIDFile, we now replace the flock() system call with fcntl() for
extending portability to Solaris. The resulting lock entity has
fundamentally different semantics.
Adding read / write locking calls, that can be blocking or not.
Adding lock status check calls.
Crating log file with PIDFile ctor.
Acquiring read lock in each spawned process; file locks are not
inherited anymore with fcntl.
Using SIGUSR1-based synchronization to mantain file lock accross fork()
calls.
Adding unit tests for new functions.

(PCP-49) Use fcntl-based file locking

---

lib/inc/pxp-agent/external_module.hpp
lib/inc/pxp-agent/thread_container.hpp
lib/src/request_processor.cc
lib/src/thread_container.cc
lib/tests/unit/thread_container_test.cc

Here we use the thread and chrono headers in cpp-pcp-client to move from
std::thread to boost::thread.

(PCP-53) Port agent to boost::thread

---

lib/inc/pxp-agent/external_module.hpp
lib/src/external_module.cc
lib/src/request_processor.cc

Here we allow modules to specify an "interpreter" field in their config
files. If this field is set, the agent will use it to execute a module
action instead of assuming that the script is executable. This allows us
to get around having to use bat files and shebang lines on different
platforms.
We do this by slightly changing the api of ExternalModule. A second
ctor is added with the config as a parameter so we can check for the
interpreter field before validating the rest of the config.
validateAndSetConfiguration becomes validateConfiguration, since
configuration is set before the method is called.

(PCP-28) Add interpreter field to module config options

---

exe/main.cc

Transition to boost::thread from std::thread missed a spot.

(maint) Use boost instead of std::thread on Windows

---

CMakeLists.txt

The logging prefix is used only when building cpp-pcp-client, making it
inconsistent to whenever the installed libcpp-pcp-client is used.

(maint) Don't pass the logging prefix to cpp-pcp-client

---

lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/util/posix/daemonize.cc

Removing unnecessary option.
Removing unnecessary Configuration::setNonExposedOptions().

(PCP-62) Remmove internal pid-dir option

---

README.md
exe/main.cc
lib/src/configuration.cc

Here we change the when we start in unconfigured mode from "no config
file is specified, the default config file doesn't exist, drop all flags
and start daemonized" to "If options are not set that we require to
connect, start unconfigured". We will continue to fail in the case of
config errors that we cannot recover from, such as parsing invalid
flags, not being able to process a given config file due to bad values,
not being able to log and (in the future) not being able to write a
pidfile.

(PCP-63) pxp-agent will always demonize when unconfigured

---

ext/debian/pxp-agent.init
ext/osx/pxp-agent.plist
ext/redhat/pxp-agent.init
ext/solaris/smf/pxp-agent.xml
ext/suse/pxp-agent.init
ext/systemd/pxp-agent.service

By default, pxp-agent now daemonizes if unconfigured, and runs as
a foreground process if invoked with --foreground.
This commit removes the unsupported --daemonize argument from the
pxp-agent SYSV init scripts and adds the --foreground argument for
the platforms where daemonization is not needed.

(PCP-69) Update service configs for daemonization by default

---

CMakeLists.txt

Prior to this changeset, execution of pxp-agent on OS X fails with ```dyld: Library not loaded:
libcpp-pcp-client.so```. To fix this, we borrow from Facter, bumping the cmake requirement to 3.2.2 and setting the CMAKE_INSTALL_RPATH based on the install prefix.

(PCP-67) Bump cmake requirement to 3.2.2, set CMAKE_INSTALL_RPATH

---

ext/osx/pxp-agent.plist

This commit updates the OSX launchd plist configuration to
move "--foreground" to its own element in the ProgramArguments
array.

(PCP-69) Fix OSX launchd plist formatting

---

CMakeLists.txt

Without this change, modules were installed to the wrong location in
packaging; rather than move it after install, allow the install to be
configured correctly in the first place. The modules were also installed
without execute permission; now install with that permission set.

(PCP-85) Allow modules install path to be set and fix permissions

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Here we remove the default flags when calling `puppet agent`. It is now
up to callers of the module to specify all relevant flags.
The previous functionality can be replaced by calling pxp-module-puppet
with a flags field like
```
["--no-usecacheonfailure",
"--no-splay",
"--show_diff",
"--no-daemonize",
"--onetime",
"--verbose"]
```

(PCP-86) Remove default flags to puppet agent call

---

lib/CMakeLists.txt
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/configuration/posix/configuration.cc
lib/src/configuration/windows/configuration.cc

Registering a handler for SIGUSR2 that will reopen the file associated
with the log file stream (new class var of Configuration), in case we
log on file on *nix platforms.
Adding new platform specific section on configuration.hpp and related
implementation files in src/configuration/posix  and /windows.
Adding reopenLogFile() method to Configuration.

(PCP-6) Reopen log file after SIGUSR2 on *nix

---

lib/src/modules/status.cc
lib/tests/unit/modules/status_test.cc

Here we fix the status action's unit tests to be able to pass when run
as a non-root user or when the default spool-dir directories don't
exist.

(PCP-83) Fix unit tests

---

lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc

Here we define HorseWhisperer options in a established order, instead
of letting std::map doing it by alphabetical order.
We now store the default options in the Configuration class in a
boost::multi_index container with two indexes: one preserves the
insertion order, the other enables access by key (the option name).
Also improving the order of options.

(PCP-82) Configuration options ordering

---

lib/src/external_module.cc
lib/src/request_processor.cc
modules/pxp-module-puppet
modules/pxp-module-puppet.bat

- Remove interpreter module config parameter
- Set correct defaults for `puppet_bin` in pxp-module-puppet
- Add .bat file required to execute pxp-module-puppet on Windows.

(PCP-96) Remove unneeded config options and set correct defaults

---

README.md
lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/util/posix/pid_file.hpp
lib/src/configuration.cc
lib/src/util/posix/daemonize.cc
lib/src/util/posix/pid_file.cc
lib/tests/unit/util/posix/pid_file_test.cc

Here we allow specifying the path of the PID file on *nix.
Note that on Windows we don't write the PID to file; we ensure that only
one instance of pxp-agent is running at time by using a mutex.
Modifying the PIDFile interface.
Checking the pidfile path.
Updating unit tests.

(PCP-78) New --pidfile option

---

README.md
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/tests/unit/configuration_test.cc

Removing --logdir option and --console-logger flag.
Introducing the new --logfile option.
README improvements.
Logging to stdout can be specified by using "--logfile -".
Changing default logging settings to continue logging on file by
default, but in case --foreground is flagged we don't error;
instead, we set the log level to none.

(PCP-79) Replace --logdir with --logfile

---

lib/src/util/windows/daemonize.cc

Without this change x86 builds fail with a static_cast error.

(maint) Fix Windows x86 builds

---

acceptance/setup/common/020_Configure_Pxp_Agents.rb

We were mkdir'ing folders for pxp-agent as the installer didn't create them.
The installer now creates these folders, so setup shouldn't.

(maint) Remove creation of pxp-agent folders during acceptance setup

---

ext/systemd/pxp-agent.logrotate

Since the pxp-agent does not write a pid file
unless daemonized, we need to use "native"
systemd facilities to signal pxp-agent.
This commit adds a systemd-specific logrotate
config that uses a systemctl facility to do
postrotate signalling of pxp-agent.

(PCP-92) Add systemd-specific logrotate config

---

ext/systemd/pxp-agent.logrotate

Prior to this commit, the systemd logrotate config's
postrotate snippet was missing the target service
parameter. This commit adds the target service.

(PCP-92) Add missing logrotate postrotate parameter

---

acceptance/setup/packages/010_Install.rb
acceptance/tests/pxp_agent_associate.rb

A PCP broker is set up as part of acceptance test pre-suite.
This commit adds an acceptance test that pxp-agent will associate with the broker when it is started as a service.
Also has a small change to pre-suite - CentOS does not have rsync by default, and rsync of the test certs to the pxp-agent host was not working.

(PCP-66) Acceptance test for associating pxp-agent with PCP broker

---

ext/debian/pxp-agent.init
ext/osx/pxp-agent.plist
ext/redhat/pxp-agent.init

Prior to this commit, some of the pxp-agent service
scripts were setting PATH. This appears to be
unneccesary. Additionally, the specific PATH that
was being set could lead to unexpected use of the
puppet-agent's "private" utilities, such as gem.
This commit removes PATH where it was set in the
pxp-agent service scripts.

(PCP-122) Don't set PATH in pxp-agent service scripts

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Here we add the flags `--onetime`, `--no-daemonize` and `--verbose` to
all puppet agent runs by default. This is done by calculating the union
between the set of passed flags and the set of default flags so that if
a default flag was set by the caller, we do not set it again.

(PCP-123) Add default flags to puppet agent run

---

.gitmodules
.travis.yml

In order to allow travis to check out the submodules, use https urls which
allow cloning with no authentication.  Committers may need to update remotes.
Fix the travis script to install gems before doing a bundle exec

Make travis tests work again

---

acceptance/setup/common/010_Setup_Broker.rb

Add polling of port 8142 to confirm the broker has started up.
Send broker's output to /var/log/pcp-broker.log instead of /dev/null so we have output for troubleshooting.
Before starting the broker, run 'lein deps' as a separate command so that time-consuming downloading of dependencies is separated from start-up time.

(maint) Improve set-up of pcp-broker in acceptance tests

---

lib/src/agent.cc

In case of an error during WebSocket connection, don't log it in Agent class,
just propagate the error which will be logged by the main function.

(PCP-5) Avoid duplicate error message when connecting

---

modules/README.md
modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Here we add a new field to the response, error_type. This field is
intended to be machine readable so that consumers of the response
message can easier determine how to react to failures.
We are also able to refactor #get_result_from_report by adding
a #make_error_result function. This simplifies it's calling convention
by removing the need for the optional error string and fail_hard
boolean. Calls that do not require the last_run_report to be parsed can
now directly call #make_error_result.

(PCP-119) Add machine readable error_type to response

---

modules/README.md
modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Here we add a version field to the output which contains the version of
the output schema.

(PCP-128) Add version field to output

---

lib/src/util/posix/daemonize.cc

Commit e0537e0289514db634dfe458075e9344f9d98f89 broke compilation on
Solaris, as stdin/stdout/stderr are macros and can't be assigned to.
The original change was to avoid cppcheck warnings. Change to checking
the return value and logging if there was a failure.

(maint) Fix compiling on Solaris

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

In the past it was possible for a run to start between checking if there
was a run and running.
Here we no longer check if the lock files exist and instead kick a run
regardless and inspect the output to determine if a run was already
underway or if puppet was disabled. We still report the same message
back to the consumer.

(PCP-117) Fix racy checks in running? and disabled?

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Passing environment entries as a hash via :custom_environment to the
Puppet::Util::Execution.execute function.
Updating spec tests.

(PCP-95) Safely pass command line options to Puppet::Util::Execution

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Here we make the `"error"` and `"error_type"` fields optional so that
the structure makes it more obvious as to when an error occurred.

(PCP-127) Make error and error_type optional in response

---

acceptance/Rakefile

Tests fail on Jenkins because genconfig is unexpectedly skipped.
genconfig is skipped depending on HOSTS or CONFIG being set in the environment.
Currently we use neither value for anything, and always use genconfig; so just remove this.(maint) Remove unused env variables from Rakefile

(maint) Remove unused env variables from Rakefile

---

lib/src/util/posix/daemonize.cc

cppcheck issues a warning when the result of freopen isn't stored. In
our case we don't care what it is, as stdin/stdout/stderr aren't managed
by us. Circumvent the warning.

(maint) Avoid cppcheck warning

---

exe/CMakeLists.txt
lib/tests/CMakeLists.txt

With cpp-pcp-client built as a static library, its dependency on WS2_32
now needs to be handled in the consumers in pxp-agent. Add the library for
unit tests and pxp-agent binary.

(PCP-138) Link Ws2_32 on Windows

---

exe/CMakeLists.txt
lib/tests/CMakeLists.txt

When we were building shared libraries, system libraries were
being included implicitly. Call them out explicitly now for unit
tests and the pxp-agent binary.

(PCP-136) Fix Solaris dependencies that were implicit

---

lib/CMakeLists.txt

We were attempting to set target properties on a target we don't create.

PCP-136 Correct target name

---

lib/tests/unit/util/posix/pid_file_test.cc

The PIDFile ctor test, section "it fails if the dir does not exist" was
causing an error on different platforms; apparently Catch was not
filtering the asserted error when the REQUIRE_THROWS macro was used.
Here we replace such macro with REQUIRE_THROWS_AS to investigate the
behaviour of the unit tests.

(PCP-136) Try to fix Catch failure with different macro

---

lib/tests/unit/util/posix/pid_file_test.cc

Removing trivial tests based on REQUIRE_THROWS_AS as they were creating
running problems on different platforms.

(PCP-136) Remove PIDFile ctor tests that assert errors

---

lib/src/external_module.cc

Mac OS X 10.9 and 10.10 builds use older versions of Clang that had
initializer list issues. Fix compilation for those compilers.

(maint) Fix compilation on older versions of Clang

---

ext/solaris/smf/pxp-agent.xml

Currently, once a Solaris pxp-agent successfully connects
to a PCP broker, the startup does not return. After 60 seconds,
SMF kills the service and places it into maintenance mode.
This commit removes `--foreground` from puppet-agent's
SMF manifest, which allows the start method to return.

(PA-46) Don't '--foreground' on startup on Solaris

---

lib/src/configuration.cc
lib/tests/unit/configuration_test.cc

When validating the configuration, we now discriminate between SSL that
don't exist and that are not readable. Adding unit tests for that.

(PCP-155) Distinguish between cert not found and not readable

---

acceptance/Rakefile
acceptance/config/aio/options.rb

Previously, acceptance was only failing in CI, but not when run locally,
and the failure was that the ca_crt.pem was never rsync'ed to the agent
node:
WebSocket configuration error (ssl-ca-cert file '/root/test-resources/ssl/ca/ca_crt.pem' not found
I believe the root cause is due to using ssh-agent on the coordinator
node. This step was only necessary so we could git clone the private
pcp-broker repo. Now that the repo is public, the step is not necessary,
and it eliminates having to interact with ssh-agent on the shared CI
coordinator.
This commit also increases the beaker log level so we can see what
commands beaker is executing.

(maint) Remove ssh-agent call

---

acceptance/setup/aio/010_Install.rb
acceptance/setup/common/020_Configure_Pxp_Agents.rb

Previously, acceptance tests were failing in CI due to the lack
of a defined SSH key needed to execute rsync on the test runner.
This commit replaces the call to rsync with the beaker helper
method `scp_to`. Since, beaker manages the SSH keys as part of
the startup process, further mention of the SSH key is not
required.

(maint) acceptance - replace rsync with scp_to

---

modules/pxp-module-puppet

If puppet_bin is configured, and contains a space, executing it will
fail attempting to find an executable with the path preceding the space.
Quote unquoted paths with spaces to fix this.

(PCP-164) Quote puppet_bin property

---

.travis_target.sh
appveyor.yml

Here we change from integrating master of cpp-pcp-client to integrating a
released version.
Though this means we may not catch issues integrating master:master, that
should be addressed with a more deliberate build target.

(maint) Use cpp-pcp-client 1.0.1 in travis and appveyor builds

---

acceptance/tests/pxp_agent_associate.rb

The test previously only checked for websocket success. It now checks for association succeeding.
The assertion on websocket success has been left in so that in the event of a failure we have more information on when it failed.

(PCP-143) Update association acceptance test to actually check for success

---

acceptance/lib/pxp-agent/config_helper.rb
acceptance/setup/common/020_Configure_Pxp_Agents.rb
acceptance/tests/invalid_ssl_config.rb
acceptance/tests/pxp_agent_associate.rb
acceptance/tests/service_stop_start.rb

Tests fail on some supported platforms due to the use of 'sed -i'.
This PR adds a helper lib file to provide constants and helper methods for pxp-agent. This includes helper methods to generate pxp-agent config JSON.
The sed statements that altered pxp-agent.conf have been replaced with beaker helper methods that replace the config file's content with generated JSON.

(PCP-169) Acceptance tests should not use sed

---

lib/CMakeLists.txt
lib/inc/pxp-agent/results_mutex.hpp
lib/src/modules/status.cc
lib/src/request_processor.cc
lib/src/results_mutex.cc
lib/tests/CMakeLists.txt
lib/tests/unit/results_mutex_test.cc

With this commit we synchronize reading and writing operations on
transaction status metadata files by non-blocking tasks and status
requests handlers.
The status query action now reads the PID file before accessing the
metadata file. In case the PID is related to a non-existent process, and
its mutex is still in the cache, the status handler will sleep for 0.1 s,
to ensure that the non-blocking task has the time to lock the mutex
and update the metadata file.
The synchronization relies on the ResultsMutex singleton that caches
mutexes named against transaction IDs.

(PCP-172) Synchronize non-blocking tasks and status handlers

---

.travis_target.sh
appveyor.yml

Reverts puppetlabs/pxp-agent#249
1.0.2 turned out to be a bad version that we will not ship in
puppet-agent. Reverting this so that travis-ci and appveyor can run
against the shipped version.

Revert "(maint) Update upstream CI cpp-pcp-client 1.0.2"

---

acceptance/tests/service_stop_start.rb

This commit adds an acceptance test to ensure that the pxp-agent
service can be enabled and started.
[skip ci]

(maint) Add acceptance test for enable service

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Better use the configured value instead of joining statedir and a fixed string.

Use lastrunreport setting instead of guessed value

---

acceptance/config/aio/options.rb
acceptance/setup/aio/010_Install.rb

The wrong package name was being installed; leading to an install of Puppet without PXP.
A correction to the beaker options is also required, while :type was not correctly set; puppet would not be available on the path when beaker tried to execute it via ssh.

(PCP-175) Fix acceptance tests on Ubuntu platforms

---

appveyor.yml

It seems that appveyor's git install with the problematic Git\bin\sh.exe
have moved, so we need to update.

(maint) Update appveyor Git moves

---

acceptance/lib/pxp-agent/config_helper.rb
acceptance/setup/aio/010_Install.rb
acceptance/tests/pxp_agent_version.rb

Puppet and pxp-agent will be in the Program Files x86 folder if Puppet is 32bit on 64bit Windows.
To support this, I've added a helper method to get the path to pxp-agent.
Removed the static strings in the pxp_agent_version test and replaced with a call to the helper.

(PCP-176) Support 32bit Puppet on 64bit Windows

---

acceptance/lib/pxp-agent/config_helper.rb

This commit adds the `/var/root` base paths to the
pxp-agent acceptance helper. It also refactors the
helpers to accommodate OSX as an option when building
paths for cert installation.
Prior to this commit, acceptance tests on OSX failed due to the
mismatch in the expected (`/root`) and actual (`/var/root`) of
the base path for the root user.
[skip ci]

(PCP-174) Acceptance - add OSX root paths to helper

---

acceptance/tests/service_stop_start.rb

We have defined the pxp-agent.conf file as required for the
pxp-agent service to start on Solaris. Therefore, the steps
in the `service_stop_start` test that test the starting of
the service in the absence of the config file need to be skipped.
See:
https://github.com/puppetlabs/pxp-agent/blob/stable/ext/solaris/smf/pxp-agent.xml#L10-L12
[skip ci]

(PCP-174) Acceptance - skip un-configured service

---

acceptance/lib/pxp-agent/config_helper.rb
acceptance/tests/invalid_ssl_config.rb

This commit removes the acceptance helper methods for building
the alt file paths for pxp-agent certs. It replaces these
methods with an additional boolean parameter on the default
file path methods. This parameter will instruct the method
whether to return the standard or alt paths based on its value.
[skip ci]

(maint) Acceptance - refactor alt helper methods

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/common/010_Setup_Broker.rb
acceptance/tests/invalid_ssl_config.rb
acceptance/tests/pxp_agent_associate.rb
acceptance/tests/pxp_agent_version.rb
acceptance/tests/service_stop_start.rb

Additionally contains a commit to ensure all our beaker test code uses 'do' code blocks for each beaker test step.

(maint) Acceptance tests should give test failures and not exceptions when checking log file

---

acceptance/tests/invalid_ssl_config.rb
acceptance/tests/pxp_agent_associate.rb
acceptance/tests/pxp_agent_version.rb
acceptance/tests/service_stop_start.rb

The tests were assuming (and our CI only uses) one agent host.
This commit has each test case iterate through the available agents and repeat the test steps on each.

(PCP-178) Acceptance tests should repeat test steps on each agent host

---

lib/tests/unit/external_module_test.cc
lib/tests/unit/modules/ping_test.cc

On Windows, GCC 5.2 complains about signed/unsigned comparisons (possibly
to keep in-line with MSVC). Update tests to fix this warning.

(maint) Fix warnings from GCC 5.2 on Windows

---

acceptance/tests/validate_file_paths.rb

This commit adds an acceptance test to validate that the pxp-agent
installation conforms to the defined file layout specifications
as declared at
https://github.com/puppetlabs/puppet-specifications/blob/master/file_paths.md

(PCP-213) Add test for file specs

---

lib/inc/pxp-agent/results_mutex.hpp
lib/src/request_processor.cc
lib/tests/unit/results_mutex_test.cc

Use constant definition from the thread abstraction in cpp-pcp-client
instead of having another one in pxp-agent.

(maint) Use PCPClient::Util::defer_lock

---

README.md
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/pxp_connector.cc
lib/tests/unit/agent_test.cc
lib/tests/unit/request_processor_test.cc

Here we add the "connection-timeout" config parameter. This allows us to
set the timeout that cpp-pcp-client passes on to websocketpp so that
users can tweak on slow networks.
This requires a cpp-pcp-client update to work.

(PCP-177) Add connection-timeout configuration option

---

ext/systemd/pxp-agent.logrotate

systemctl is either in /bin or /usr/bin depending on whether or not
you're running on deb-based systems. Those directories should always be
in your path so there's no need to specify the full path for systemctl.

(PCP-196) Remove full path for systemctl in logrotate

---

acceptance/Rakefile

If Jenkins defines both TEST_TARGET and CONFIG for beaker host configuration then CONFIG should be ignored and TEST_TARGET should be used.

(PCP-198) Acceptance should use TEST_TARGET ahead of CONFIG

---

lib/src/request_processor.cc

As indicated in the docs and in puppet-specifications, the suffix for
module configuration files must be ".conf", not ".cfg".

(PCP-238) Fix suffix used to match module config

---

CHANGELOG.md

* Vendoring cpp-pcp-client 1.0.1 for consistency with puppet-agent 1.3.3 packaging.
* Update CHANGELOG.md.

(maint) Prepare for releasing 1.0.2

---

acceptance/lib/pxp-agent/test_helper.rb

Fixing the log message that acceptance tests use to check whether the
session association succeeded or not.

(maint) Fix wrong regex for association acceptance test

---

modules/README.md
modules/pxp-module-puppet.md

Here we formalize and extend the operational requirements for I/O,
introduce the metadata schema, and rename a few metadata entries.
The interface for external modules is here extended in order to allow
pxp-agent to put the modules in charge of writing their output to file.
[skip ci]

(PCP-240) Formalize and extend external modules' interface

---

acceptance/setup/common/010_Setup_Broker.rb

Here we pin pcp-broker's version to master just before the merge of
PCP-195
PCP-195 starts populating the optional 'in-reply-to' header, which
pcp-cpp-client:stable doesn't allow for.

PCP-249 pin version of pcp-broker

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/service_stop_start.rb

Master currently has the same acceptance code as stable, but pxp-agent has different behaviour on these branches. This commit:
* Has the stop/start service test expect service stopped instead of running (unconfigured) in the case of no config file
* Expect the capitalisation of the assocation success log message that pxp-agent will actually use

(maint) Fix acceptance to reflect changes between master and stable

---

acceptance/lib/pxp-agent/test_helper.rb

When ruby-pcp-client has client.connect() called with the default timeout (0), it might fail due to thread logic.
The workaround (this commit) is to specify a non-zero timeout value.
Also add checking of the result of connect and raise an exception if it doesn't return true.

(maint) Acceptance - Workaround for PCP-253 (PCP client.connect)

---

acceptance/Rakefile
acceptance/config/aio/options.rb
acceptance/lib/puppet/acceptance/common_utils.rb
acceptance/setup/aio/pre-suite/010_Install.rb
acceptance/setup/common/035_StartPuppetServer.rb
acceptance/setup/common/040_ValidateSignCert.rb

Remove references to "package" test setup in Rakefile.
Use beaker to install puppet-agent instead of lib code in this repo.
Have agent nodes sign themselves against puppet-server on the master node.

(PCP-198) Acceptance pre-suite improvements

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

The pxp-module-puppet's run action can now save its standard output / standard error / exit code to files specified in the action's input.

(PCP-251) support for saving stdout/stderr/exitcode to files

---

lib/inc/pxp-agent/external_module.hpp
lib/inc/pxp-agent/module.hpp
lib/src/external_module.cc
lib/src/module.cc
lib/src/modules/echo.cc
lib/src/modules/ping.cc
lib/src/modules/status.cc
lib/tests/resources/broken_modules/reverse_broken
lib/tests/resources/modules/check_output.rb
lib/tests/resources/modules/failures_test
lib/tests/resources/modules/reverse_valid
lib/tests/unit/external_module_test.cc
lib/tests/unit/modules/status_test.cc

With this PR, we rely on external modules for writing action output to file,
in case of non-blocking requests.
This is achieved by using the new interface for external modules.
ExternalModule now uses the leatherman::execution::execute variant
that only processes PID, without processing stdout/stderr.

(PCP-252) Let external modules write their output

---

lib/src/external_module.cc

As external modules can now return "5" in case they fail to write their
output, JsonContainer must be correctly instantiated in case there's no
output.
Also, external modules can return no output in case of error.
Ensuring JsonContainer is instantiated with "null" string in that case.
The validation is performed after that, by the parent Module class.

(maint) ExternalModule deals with empty module's output

---

.travis_target.sh
appveyor.yml

Flagging the build option that enables virtual functions of PXPConnector
and related unit tests that rely on mocking the PCP Connector logic.

(maint) Set cmake's -DTEST_VIRTUAL for Travis/Appveyor

---

lib/tests/unit/request_processor_test.cc

Here we fix the request_processor_test.cc tests that were relying on
MockConnector without checking the TEST_VIRTUAL macro. They now safely
use the PXPConnector class as they don't rely on any WebSocket
connection.

(maint) Don't use MockConnector without TEST_VIRTUAL

---

lib/CMakeLists.txt

pxp-agent uses Boost.Thread directly, which on some platforms has a
dependency on librt. Previously it picked up the dependency as a
side-effect of using Leatherman, which is fragile when using Leatherman
shared libraries and Boost static libraries.

(maint) Add dependency on librt

---

ext/solaris/smf/pxp-agent.xml

Prior to this change the pxp-agent service was configured with a dependancy
on pxp-agent.conf which doesn't exist imediately following an upgrade of PE.
This state results in the service not starting as expected until the first
puppet run following the upgrade.
This commit removes the dependancy on pxp-agent.conf which allows the service
to start.

(PE-13918) Solaris pxp-agent stopped after 2015.2.3 to 2015.3.x upgrade

---

lib/src/pxp_schemas.cc

Removing that entry as is not in the specs anymore.
[skip ci]

(maint) Remove job_id entry from RPC Error schema

---

modules/README.md

Making it clear in the modules interface specs that pxp-agent will not
mark an action as failed by considering the action's exit code.
Instead, an action will succeed whenever its results on stdout are
validated by using the "results" JSON schema provided by the action's
metadata.
[skip ci]

(PCP-202) Module's interface: success when results are valid

---

CMakeLists.txt
lib/CMakeLists.txt

librt and Boost.Chrono are dependencies of pxp-agent, which need to be
included explicitly on AIX.

(maint) Fix dependencies on AIX

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/run_puppet.rb
acceptance/tests/pxp_agent_associate.rb

Check pcp-broker's inventory to see if pxp-agent is included; instead of grepping pxp-agent.log, which is subject to change at any time
[skip ci]

(PCP-167) Change acceptance tests to not rely on logs to assert association

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp_agent_associate.rb

PCP-167 changed the tests to check assocation with pcp-broker instead of grepping pxp-agent log for association log entries.
This occasionally fails in CI as the agent does not appear as associated with the broker.
This commit adds retry logic so that the pcp-broker inventory is checked a number of times before failing.
[skip ci]

(maint) Acceptance tests need to allow time for agent association with broker

---

modules/pxp-module-puppet
modules/pxp-module-puppet.md
modules/spec/unit/modules/puppet_spec.rb

Information obtained from a puppet run is now separated from messaging by the ```pxp-module-puppet``` in the module's output.

(PCP-206) clearer structure of pxp-module-puppet output

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/common/010_Setup_Broker.rb
acceptance/tests/reconnect_after_broker_unavailable.rb

This PR addresses the reconnect_after_broker_unavailable.rb acceptance test failing CI on master
PCP-293 - bring the test over to stable; it should not have been only on master
PCP-294 - Workaround for PCP-294, when the pcp-broker port becomes available; query pcp-broker for its state, and do not continue with the test until it reports "running"

(PCP-293 & PCP-294)

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/common/010_Setup_Broker.rb

A couple of minor improvements:
* pcp-client should be set to debug loglevel if beaker is using debug logging
* The pre-suite code should not have its own code for starting pcp-broker; especially now that the helper lib has code to test pcp-broker on startup

(maint) Improve PCP broker and client usage in acceptance

---

acceptance/lib/pxp-agent/test_helper.rb

test_helper.rb has mismatching quote characters in the run_pcp_broker method

(maint) Fix bad string quoting in acceptance helper

---

acceptance/lib/pxp-agent/test_helper.rb

An intermittent failure in test_helper/connect_pcp_client in CI might be due to the retry logic re-using the same PCP::Client instance.
This commit changes the retry logic so that a new PCP::Client instance is used for each attempt.
[skip ci]

(maint) Acceptance - restructure retry logic for PCP client

---

acceptance/Gemfile
acceptance/lib/pxp-agent/test_helper.rb

Make use of the (not yet released) 0.2.0 feature of `PCP::SimpleLogger` so we can inspect the state of the client object should it not be connected and give more context as to why the connection failed.

Make use of ruby-pcp-client 0.2.0

---

acceptance/tests/pxp-module-puppet/run_puppet_result_changed.rb

Use pxp-module-puppet to run puppet with the expected result being 'changed'
[skip ci]

(PCP-227) Acceptance test of pxp-module-puppet run with 'changed' result

---

ext/systemd/pxp-agent.service

The behavioural changes around PCP-207 and its testing in PCP-230
expect that the pxp-agent will be able to spawn long-running processes
to run actions in which have a life independent of the pxp-agent
process that spawned them.
This is defeated by systemd's default KillMode being control-group,
which will kill these long-running processes when shutting down the main agent
process.
Here we switch KillMode to process, so we only kill the pxp-agent as intended.
https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=

PCP-288 When stopping pxp-agent, only stop the agent

---

acceptance/lib/pxp-agent/test_helper.rb

When using raise for flow control we may be leaking the eventmachine
reactor thread, which makes it hard to reason about the lifecycle of a
subsequent run.
Here we move the stop_event_loop and thread join into an ensure
block, so we close down the eventmachine context when signalling
hitting the Timeout stuff.

(maint) ensure EventMachine is stopped when raising

---

acceptance/lib/pxp-agent/test_helper.rb

Here we extract methods to start and stop the eventmachine thread that ruby-pcp-client needs, then add some additional exception handling and state checks to investigate current issues with non-running reactors.

Add helpers to wrap eventmachine use

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

The input for the pxp-module-puppet's run action is not validated thoroughly enough. This commit improves it just a little bit.

(PCP-315) pxp-module-puppet input validation

---

modules/pxp-module-puppet

There was a race condition between creating the exitcode file (which pxp-agent uses to determine if a pxp-module-puppet execution finished) and the actual exit of the pxp-module-puppet process (which implicitly flushes its output). This could lead (and led) to pxp-agent reading incomplete output of the pxp-module-puppet.
To prevent this we flush the output of pxp-module-puppet explicitly before writing the exitcode file.

(PCP-317) flush pxp-module-puppet output explicitly

---

lib/tests/resources/modules/check_output.rb

Implement the same change as was recently added to the pxp-module-puppet.

(PCP-317) flush output of test modules explicitly

---

acceptance/config/aio/options.rb
acceptance/lib/pxp-agent/config_helper.rb
acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/common/050_Setup_Broker.rb
acceptance/setup/common/060_Setup_PCP_Client.rb
acceptance/tests/pxp-module-puppet/run_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_result_changed.rb
acceptance/tests/pxp_agent_associate.rb
acceptance/tests/reconnect_after_broker_unavailable.rb
acceptance/tests/service_stop_start.rb

Change the acceptance tests to use Puppet generated SSL certs instead of our test fixture certs.
For pcp-broker; the puppet certs are copied onto the standard test cert paths so that no change to pcp-broker code is needed.
Adds a pre-suite class to generate certs for the test executor so that it can certify itself when connecting pcp-client.
[skip ci]

(PCP-296) Acceptance tests should use Puppet generated SSL certs

---

lib/tests/component/external_modules_interface_test.cc

ExternalModule waits 100 ms before processing the output of a
non-blocking test; here, we're adding an extra pause to the component
tests in order to avoid transient failures when testing the
non-blocking response.
Note that the component tests are asynchronous; they are executed only
when the TEST_VIRTUAL flag is enabled.

(maint) Consider output processing delay in component test

---

lib/src/external_module.cc

Solaris keeps track of the state of the system services by employing so called contracts. A contract is effectively a group of processes. Each service has its own contract. When a service starts a new process it is by default a member of the service's contract. When a service is restarted all processes in its contract are killed (or at least the system waits until they exit).
This behavior isn't the desired one for ```pxp-agent``` as we want the modules it spawns to outlive it in case it is restarted.
The solution is to make sure the modules are executed in their own contracts so that they are not killed when the ```pxp-agent``` service is restarted. In this commit we achieve this be executing the modules via the ```ctrun``` command.

(PCP-308) run modules in own contracts on Solaris

---

.gitignore
lib/tests/common/mock_connector.hpp
lib/tests/component/external_modules_interface_test.cc

With this commit we add a function to check whether the external module
run finished by looking at the exit code file.
Removing the unnecessary pause from the bloking tests.

(PCP-340) Wait for the module completion in component tests

---

exe/main.cc
lib/inc/pxp-agent/agent.hpp
lib/src/agent.cc
lib/src/configuration.cc
lib/tests/main.cc

Retrying to connect in case of errors during Session Association; that
is done after a random pause in the  [5 s, 10 s] interval.
Handling Session Association failures.

(PCP-338) Handle Associate Session errors

---

lib/src/util/posix/daemonize.cc

Removing the std::move() call when returning the PIDFile unique_ptr from
the daemonize() function, to avoid clang error during compilation
(clang-703.0.29 seems to be more restrictive). Note that unique_ptr only
supports move assignments, so the std::move() call was redundant.

(maint) Remove move() when returning unique_ptr

---

lib/tests/unit/thread_container_test.cc

Adding a prefix for the names of threads created for ThreadContainer, to
avoid errors due to duplicate names.

(maint) Add name prefix for ThreadContainer unit tests

---

modules/README.md

For external modules, require that the metadata action is executed when
the module is invoked with "metadata" as its only argument.

(PCP-284) In modules interface, specify "metadata" arg

---

acceptance/lib/puppet/acceptance/common_utils.rb

This commit adds puppet-agent config to the acceptance setup, to ensure that puppet agent uses the hostname that beaker is expecting as the agent certname.
This avoids failures when an agent host has multiple hostnames and puppet agent generates certs for a hostname other than what beaker expects.
[skip ci]

(PCP-360) Acceptance: puppet-agent should use beaker hostname as certname

---

acceptance/tests/invalid_ssl_config.rb
acceptance/tests/service_stop_start.rb

On OSX, the pxp-agent service remains running even if the executable exits.
Therefore our acceptance tests for invalid pxp-agent.conf values should not expect the pxp-agent service to be stopped.
[skip ci]

(PCP-305) Acceptance tests on OSX should not expect a stopped service

---

acceptance/Rakefile

The current version of beaker-hostgenerator (0.x) assumes EL if you request CentOS.
This will be fixed in the next major release (1.0) of beaker-hostgenerator.
In the meantime, we need to add an option to explicitly use v1.0's OS handling.
This fixes PCP-359 where the acceptance tests failed on CentOS4 because beaker-hostgenerator gave us el4 instead, and beaker refused to install puppet-agent.
[skip ci]

(PCP-359) Fix confusion between EL and CentOS in acceptance host generation

---

acceptance/Gemfile
acceptance/lib/pxp-agent/test_helper.rb

ruby-pcp-client 0.3.0 adds a long-missing PCP::Client#close method
to shut down a client after we're done with it.
Here we switch to using this close method with a long-running
eventmachine reactor thread, avoiding the painful races caused by
trying to manage client lifecycle by restarting the supervising
eventmachine.

PCP-362 use PCP::Client#close rather than EM weirdness

---

acceptance/config/aio/options.rb
acceptance/setup/common/005_SyncTime.rb

As part of the pre-suite for the acceptance tests, ensure that all hosts have their time synced.
[skip ci]

(PCP-364) Acceptance - sync system time on hosts

---

acceptance/lib/pxp-agent/test_helper.rb

It's possible for one connection attempt to crash the eventmachine thread;  if
that happens on say connection attempt 2 of 10, attempts 3 through 10 are
guaranteed to fail.  Here we reduce the impact of this by checking we have an
eventmachine reactor in the connect helper before every attempted connection.

PCP-329 assert there's an eventmachine on every connect

---

acceptance/Gemfile

Update the acceptance Gemfile to use at least version 0.3.1 of ruby-pcp-client.
That version contains improvements to the usage of EventMachine.
[skip ci]

(PCP-329) Update ruby-pcp-client to pick up EventMachine improvements

---

acceptance/tests/invalid_ssl_config.rb

(PCP-307) Acceptance tests should expect 'maintenance' service state on Solaris

---

README.md
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/tests/unit/configuration_test.cc
lib/tests/unit/util/posix/pid_file_test.cc

- README change: required leatherman version
- Style changes
- Remove HW alias from Configuration header
- Use boost::format for error messages, to make things clearer
- Remove duplicated code from Configuration functions

(maint) Refactor Configuration

---

README.md
lib/src/configuration.cc
lib/tests/unit/configuration_test.cc

Creating the spool directory at start if it doesn't exist.
This is done in order to facilitate running pxp-agent without super user
privileges.
Also, new unit tests are added.

(PCP-345) Create spool dir if needed

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/invalid_ssl_config.rb
acceptance/tests/pxp-module-puppet/run_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_agent_disabled.rb
acceptance/tests/pxp-module-puppet/run_puppet_result_changed.rb
acceptance/tests/pxp_agent_associate.rb
acceptance/tests/reconnect_after_broker_unavailable.rb
acceptance/tests/restart_host_run_puppet.rb

Here we add a helper to show logs on assertion failures, and wrap the `is_not_associated?` `is_associated?` `assert` calls in it, to add context to the periodic failures we are tracking.

PCP-355 show logs on failures

---

acceptance/lib/pxp-agent/config_helper.rb
acceptance/tests/invalid_ssl_config.rb
acceptance/tests/restart_host_run_puppet.rb

PCP-370 will remove the test fixture SSL certs in the test-resources folder. This PR removes all usage of those certs from the pxp-agent acceptance tests

(PCP-375) Remove usage of test fixture SSL files from acceptance tests

---

acceptance/Gemfile
acceptance/lib/pxp-agent/test_helper.rb

0.4.0 adds ssl verification, so we need to pass the ssl_ca_cert when we
construct the PCP::Client

(maint) Update ruby-pcp-client to 0.4.0

---

acceptance/setup/common/005_SyncTime.rb

QENG-3786 is a bug with beaker's timesync method - it will fail on OSX due to ntpd service already running.
Until QENG-3786 is fixed, this commit skips attempting timesync on OSX hosts.
[skip ci]

(PCP-376) Acceptance - do not attempt timesync on OSX

---

lib/tests/main.cc

Removing the Catch's applyCommandLine() and passing CLI arguments
directly to the Session::run() function; note that setting ConfigData
showDurations to "Always" works in the same way as it's not changed by
our CI pipeline via CLI.

(maint) Make tests compatible with leatherman 0.4 and 0.5

---

README.md

Adds some simple instructions for using the default SSL certs in
pcp-broker to run against the broker's test setup.

(maint) Add section on running against a test broker

---

lib/src/configuration.cc

After changes for PCP-345, Configuration did not update the spool-dir
entry with the expanded path in the HorseWhisperer singleton; this
was causing external modules runs to fail to write in the results
directory.

(PCP-379) Store expanded --spool-dir in HW singleton

---

cmake/Findcpp-pcp-client.cmake

This is needed on OS X after PCP-372.

(maint) Look for .dylib in Findcpp-pcp-client.cmake

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb

This adds a new test case where we kick off a non-blocking Puppet agent run; and then terminate pxp-agent in the middle of the agent run; then assert that when the run completes and pxp-agent is once again running; we can report on the status of the run.
This required adding a new test helper to perform a non-blocking PXP request
[skip ci]

(PCP-230) Acceptance - restart pxp-agent during Puppet run

---

ext/pxp-agent.logrotate

In absence of /var/run/puppetlabs/pxp-agent.pid, log rotation used to exit 1.
A valid shell conditional now prevents this false negative.

(PCP-196) Fix log rotation on Ubuntu 14.04 LTS

---

lib/CMakeLists.txt

On Windows, Leatherman's logging/locale libraries need to be contained in
the same DLL. That can be done by either making them shared libraries, or
by creating a monolithic pxp-agent binary.
Currently our packaging makes it messy to use shared Leatherman DLLs, and
they don't bring us any advantages. Make it simple to use cpp-pcp-client
as a static library instead so we can produce a smaller package.

(maint) Enable builds with static cpp-pcp-client

---

lib/CMakeLists.txt

Fixes in Leatherman made explicit pthread dependencies unnecessary.
Remove them.

(PCP-270) Remove outsourced pthread dependency

---

lib/CMakeLists.txt

Reverts puppetlabs/pxp-agent#410
Still required on AIX.

Revert "(PCP-270) Remove outsourced pthread dependency"

---

CMakeLists.txt
exe/main.cc
lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/pxp_schemas.hpp
lib/src/action_request.cc
lib/src/action_response.cc
lib/src/agent.cc
lib/src/configuration.cc
lib/src/configuration/posix/configuration.cc
lib/src/external_module.cc
lib/src/module.cc
lib/src/modules/ping.cc
lib/src/pxp_connector.cc
lib/src/request_processor.cc
lib/src/results_mutex.cc
lib/src/results_storage.cc
lib/src/thread_container.cc
lib/src/time.cc
lib/src/util/posix/daemonize.cc
lib/src/util/posix/pid_file.cc
lib/src/util/windows/daemonize.cc
lib/src/util/windows/process.cc
locales/pxp-agent.pot

Enable the creation of the .pot file that includes the strings that
we want to translate. Don't enable localization now; we'll do that on
PCP-257.
Use leatherman::locale::format() and translate() for the strings that we
want to translate.
Use "{}" instead of "%%" for string interpolation.
Don't use leatherman::util::plural(); we'll deal with plurals once we
enable localization on PCP-257.

(PCP-371) Spike i18n support

---

acceptance/Rakefile

ci:test:aio was failing in the puppet-agent pipelines when a static hosts file (e.g. aix-71-power.yaml) was needed.
This commit updates Rakefile to work with ENV values passed from CI in the same way as all other puppet-agent components.
[skip ci]

(PCP-381) Fix usage of env values in acceptance Rakefile

---

appveyor.yml

AppVeyor images were updated to include software that installs OpenSSL
binaries to `C:\Windows\System32`.
https://msdn.microsoft.com/en-us/library/7d83bc18.aspx describes the
Windows search path, which puts the Windows system directory before
PATH. The easiest way to ensure the libraries are loaded earlier is to
put them in the same directory as the test executable, so do that.

(maint) Fix up AppVeyor

---

lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
locales/pxp-agent.pot

Uses alias to original type in HorseWhisperer for FlagType so they're
guaranteed to be in-sync. Also uses explicit assert to ensure we always
hit valid switch statements; a new option type will hit `assert(false)`.

(maint) Cleanup HorseWhisperer enum use

---

exe/main.cc
lib/inc/pxp-agent/action_request.hpp
lib/src/action_request.cc
lib/src/action_response.cc
locales/pxp-agent.pot

(maint) Default to pass constructor arguments by value
(maint) Fix minor issues from i18n work

(maint) C++ Style Cleanup

---

lib/src/pxp_connector.cc
lib/src/request_processor.cc
lib/src/results_storage.cc
lib/src/thread_container.cc
locales/pxp-agent.pot

Until Leatherman adds plural i18n helpers, we don't want a release to
backtrack on pluralizing message strings. Restore basic pluralization in
a way similar to what the i18n helpers will do.

(maint) Restore plural messages

---

lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/pxp_connector.cc
lib/tests/common/mock_connector.hpp
lib/tests/unit/agent_test.cc
locales/pxp-agent.pot

Adds the failover-ws-uri option. When specified, will use that as a fallback when the primary broker is unavailable. To avoid split-brain installations, only allow one broker to be active at a time.

(PCP-383) Add broker failover

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

This commit makes it possible to run puppet under a non root user.
Previously this was not possible because puppet failed to expand the user home directory. This was due to the environment cleaning performed by the `Puppet::Util::Execution.execute` function used for the puppet run execution which included unsetting of the `HOME` environment variable.
This patch solves that by fixing the environment (re-adding the necessary environment variables to it) after the cleaning. The values of the re-added variables are obtained by reading the pwentry corresponding to the current effective user id.

(PCP-349) support running puppet as non-root

---

acceptance/tests/restart_host_run_puppet.rb

This change tries to make the restart_host test more robust by using two
sleeps.  One to ensure the agent is actually rebooted (see BKR-812) and
one to retry up to 10 times until pxp-agent is back up.
[skip ci]

(PCP-428) restart_host_run_puppet.rb transient fails on ubuntu1404

---

acceptance/tests/restart_host_run_puppet.rb

Last commit against this test, to fix some flakiness let a missing
variable definition squeak through, in the exception handling for
timeout.  This commit remedies this.

(PCP-428) define missing variable in restart_host_run_puppet test

---

acceptance/tests/restart_host_run_puppet.rb

The previous commit works around some flaky host and pxp-agent restart
issues by using retry_on(), but did not take into account puppet command
pathing issues in windows.  this commit fixes this.

(PUP-428) fix restart_host test on windows agents

---

ext/systemd/pxp-agent.logrotate

If logrotate ran and pxp-agent wasn't running it would fail to kill it. Now it
will only try to kill it if it's running.

(PCP-453) Only kill pxp-agent if it's running

---

lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/pxp_connector.cc
lib/tests/common/mock_connector.hpp
lib/tests/unit/agent_test.cc
locales/pxp-agent.pot

Adds the `allowed-keepalive-timeouts` option, with a default of 2. The
option is used to decide how many consecutive keepalive responses can be
lost before closing the connection and trying to reconnect. With the
default of 2, the connection will be closed after 3 lost keepalive
responses; the agent will then attempt to reconnect to the broker and/or
failover broker.

(PCP-423) Add `allowed-keepalive-timeouts` option

---

lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/pxp_connector.hpp
lib/src/configuration.cc
lib/src/pxp_connector.cc
lib/tests/common/mock_connector.hpp
lib/tests/unit/agent_test.cc
locales/pxp-agent.pot

The `association-timeout` option is now used to set the timeout for the
overall Association process (default to 15 s).
The old `association-timeout` (ttl for the Association request) can now
be specified by the `association-request-ttl` option (default to 10 s).
Renaming the `pcp-message-timeout` option to 'pcp-messag-ttl', for
consistency with the other ttl option.

(PCP-452) Add option to configure Association timeout

---

lib/src/agent.cc

Revert to using `monitorConnection`. It ensures exceptions thrown during
monitoring are propagated to the caller.

(PCP-463) Restore blocking monitor action

---

lib/CMakeLists.txt

This avoids compilation failure during parallel builds (as in `make -j`)
when horsewhisperer is unpacked after starting to compile source for
libpxp-agent.

(maint) Add libpxp-agent dependency on horsewhisperer

---

README.md
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/tests/resources/config/bad-uri.cfg
lib/tests/resources/config/duplicate.cfg
lib/tests/resources/config/multi-broker.cfg
lib/tests/unit/configuration_test.cc
locales/pxp-agent.pot

Changes broker-ws-uris to only be settable via a config file. Also
clarifies how it and broker-ws-uri interract, and adds documentation in
the README.

(PCP-405) Make broker-ws-uris a config file only option

---

modules/pxp-module-puppet
modules/pxp-module-puppet.md
modules/spec/unit/modules/puppet_spec.rb

Ignoring the `env` array to avoid letting the user to set custom
environment variables as we currently don't have a use case for that.
The `env` entry of the JSON metadata's input object remains defined
for backwards compatibility, but it's not a required entry anymore.
Thus, pxp-module-puppet interface remains the same; in the future we may
want to completely remove the `env` entry, but that would require
bumping the interface version.
Updating unit tests.
Updating docs.

(PCP-472) Ignore pxp-module-puppet `env` input arg

---

acceptance/setup/common/005_SyncTime.rb

Our vmpooler images for Ubuntu 14.04 now have the ntp service running.
This causes the pre-suite step 005_SyncTime.rb to fail, as beaker's timesync method fails if ntp is running as a service.
This commit skips timesync for Ubuntu hosts. It intentionally skips any Ubuntu host as I found that 15.10 and 16.04 also had ntp running.
[skip ci]

(PCP-478) Acceptance pre-suite should skip timesync for Ubuntu

---

CMakeLists.txt
modules/pxp-module-puppet.bat

The pxp-module-puppet batch wrapper needs to be installed on windows platforms
to correctly load the module.

(PCP-479) Update pxp-agent to install batch wrapper

---

acceptance/Rakefile
acceptance/config/aio/options.rb
acceptance/lib/pxp-agent/config_helper.rb
acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/common/050_Setup_Broker.rb

also: 
(maint) acceptance: move helper config option out of Rakefile
* make default log_level verbose for beaker

(PCP-431) pxp agent acceptance should support a failover pcp broker

---

acceptance/tests/failover/intentional_shutdown_failover.rb

do not merge prior to PR-444
* configure agents for multiple broker uris
* ensure association with primary broker
* stop first broker, start replica
* ensure association with replica
[skip ci]

(PCP-430) Automate pxp-agent broker failover acceptance test

---

acceptance/lib/pxp-agent/config_helper.rb

add workaround for tests which need a working broker URI but may not
have started it yet.
[skip ci]

(PCP-431) fix previous acceptance commit

---

acceptance/lib/pxp-agent/config_helper.rb

Broker_hosts can come through as hashes, ips, hostnames, or beaker
hosts.  We need to ensure we trigger failover uri's when using a beaker
host.
[skip ci]

(PCP-430) previous fix for other tests broke the failover test

---

lib/src/module.cc
lib/tests/unit/external_module_test.cc

Without this change stderr was inadvertently left out of the module
response. Ensure it's included.

(PCP-493) Ensure stderr is returned in module response

---

.travis_target.sh

Our use of gettext requires version 0.19. Ensure it's installed and used
every time.

(maint) Fix gettext in Travis CI

---

acceptance/tests/restart_host_run_puppet.rb

The test will hang beaker indefinitely. This commit also fixes a bug with the existing test where it wasn't correctly testing the need to skip.
[skip ci]

(PCP-508) Skip host restart test for CiscoNX

---

acceptance/tests/restart_host_run_puppet.rb

restart_host_run_puppet.rb will fail (and ruin any subsequent tests) on Arista due to the device applying a system image on reboot.
This commit adds a skip_test clause for Arista.
[skip ci]

(PCP-515) Acceptance - skip restart_host_run_puppet.rb on Arista

---

acceptance/tests/failover/timeout_failover.rb

Previously, this test checked that the primary no longer has our agents
associated.  But this can fail, in a flaky fashion, on windows, when the
broker may or may not receive socket close due to different TCP
defaults.
[skip ci]

(PCP-457) Acceptance: remove primary dis-association check

---

acceptance/tests/restart_host_run_puppet.rb

We currently skip the host restart test on Arista VMs due to their reboot behaviour.
Fixing this will require some RE work - this commit simply updates the ticket reference in the test from PCP-515 to RE-7673
[skip ci]

(PCP-515) Acceptance - update ticket reference for skipped test on Arista

---

acceptance/tests/pxp_agent_version.rb

The Windows MSI layout changed to sharing binaries for C++ applications.
That means pxp-agent.exe now relies on files in puppet/bin. Update the
test to include that in PATH.
For now hard-code in the test. It's not trivial to amend the
privatebindir in config/aio/options.rb, since the setting is
platform-dependent. This might eventually live in Beaker, but since it's
only needed for this test that may not be worth it.

(maint) Fix path for pxp-agent using new Windows MSI layout

---

modules/pxp-module-puppet
modules/spec/fixtures/last_run_report.yaml
modules/spec/unit/modules/puppet_spec.rb

Support parsing a last_run_report.yaml file containing Puppet objects -
sometimes introduced by resource types that don't serialize properly -
by dropping them from the report. We only look at a few known fields, so
it's safe to ignore the rest of the report.

(PCP-542) Allow parsing last_run_report with Puppet objects

---

acceptance/setup/common/050_Setup_Broker.rb

The acceptance test suite relies on being able to download all the dependencies for pcp-broker from clojars.org.
This commit changes the 'lein deps' command to use a new profile that will also add our internal clojar repo URL.
[skip ci]

(PCP-354) Acceptance - pcp-broker should use internal mirror for deps

---

.travis.yml
modules/Gemfile
modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

In a C/POSIX locale, Puppet will still output unicode as UTF-8. Ensure
we parse as UTF-8 despite the locale. Without this change regex
comparison throws an exception when attempting to compare against
ASCII_8BIT output.

(PCP-545) Force interpreting Puppet's output as UTF-8 in C/POSIX locale

---

acceptance/tests/pxp-module-puppet/run_puppet_nonASCII.rb
acceptance/tests/pxp-module-puppet/run_puppet_result_changed.rb

PCP-494 added a UTF8 character into an existing pxp-module-puppet test case to ensure we support them (commit 85e36fb).
This is currently failing on some platforms in CI (see PCP-558).
This PR splits the test with a UTF8 character into its own test, so it gets its own result in our result matrices. It also adds a specific assertion so that if PCP-494 does regress, we get an explicit assertion failure for it.
[skip ci]

(PCP-558) Give UTF8 test case its own acceptance test

---

acceptance/tests/pxp-module-puppet/run_puppet_nonASCII.rb
modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Puppet output is always UTF-8 encoded. Even if the locale implies
otherwise, interpret output as UTF-8.

(PCP-545) Always force Puppet output to UTF-8

---

acceptance/Rakefile

When specifying BEAKER_HOSTS, TEST_TARGET does not need to be set.
However, the Rakefile errors if run without TEST_TARGET set. Update to
check that TEST_TARGET is not nil before trying to check start_with.

(maint) Fix Rakefile when specifying BEAKER_HOSTS

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb
acceptance/tests/pxp-module-puppet/run_puppet_during_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

When `pxp-module-puppet run` is triggered and Puppet was already
running, the module would previously identify the failure and return an
error message saying Puppet could not be run because another run was in
progress. This leads to a potentially slow feedback cycle of retrying
Puppet until it can run, when all the module user wants is to ensure a
Puppet run happens with the arguments they specified.
Change pxp-module-puppet to wait until the prior Puppet run completes
and attempt to run again until it succeeds or encounters a different
error.

(PCP-549) Wait for other Puppet runs to finish

---

.travis_target.sh

The previous change referenced the wrong file. Fix it so it deletes the
correct gettext pot file, ensuring CI will test regenerating it.

(maint) Fix Travis script to ensure pot file is regenerated

---

acceptance/tests/pxp-module-puppet/run_puppet_during_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb

On certain platforms the shell command to run Puppet in the background
was incorrect, leading to Puppet timing out. Fix shell commands.

(PCP-571) Fix tests failing with Puppet timing out

---

.travis_target.sh
acceptance/lib/pxp-agent/test_helper.rb

Periodically starting the broker will take a long time. It appears to be
downloading dependencies when `lein tk` is run, despite `lein deps`
being previously run. This is probably because we ran `lein with-profile
internal-mirrors deps`, but then run `lein tk` with a different profile.
Update to run `lein with-profile internal-mirrors tk`.
Also cherry-picks up fixing the Travis CI script. I apparently targeted that at master by accident.

(PCP-557) Ensure broker runs with internal mirrors

---

acceptance/tests/restart_host_run_puppet.rb

Don't restart the broker when running tests to restart pxp-agent. This
prevents restarting the agent host when that host also includes the
master role, so that we only restart agents that don't include the
broker.

(PCP-577) Don't run tests that restart broker

---

acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb

CiscoNX tests don't run as root. Ensure we read the lockfile using
Beaker methods to pickup any helpers (like running sudo).
[skip ci]

(PCP-576) Ensure cisconx tests can read lock file

---

acceptance/tests/restart_host_run_puppet.rb

Due to a bug (tracked by QENG-4371) the fedora hosts in our VM Pooler take
anywhere from 5 to 20 minutes to reboot, causing this test to time out and fail
consistently in Puppet Agent testing. Until this is resolved, the test running
on Fedora is causing consistent triage effort in Agent with little value. This
commit follows the existing pattern for excluding agents to exclude the Fedora
platform from testing. The long reboot times have been seen across fedora
arches and versions so this generically excludes the platform rather than a
specific version/arch target. Secondarily, we are also seeing sporadic issues
on occassion reconnecting to the broker after reboot (PCP-585), which is also
impetus for this change.
Signed-off-by: Moses Mendoza <moses@puppet.com>

(PCP-605) (PCP-585) Disable restart_host_run_puppet on Fedora

---

acceptance/setup/common/005_SyncTime.rb

BKR-960 is a beaker bug where the timesync helper method doesn't support cisco xr ios.
As a workaround, this commit just skips timesync for that platform.
This leaves the tests at risk of failing due to clock differences, but allows the tests to complete otherwise.
[skip ci]

(BKR-960) Skip timesync for ciscoxr-64a

---

appveyor.yml

Stop fighting against AppVeyor including OpenSSL and use the
pre-installed version. Also restrict PATH to only use known paths. This
fixes builds that accidentally loaded a different OpenSSL from
C:\Windows\system32.

(maint) Use AppVeyor OpenSSL

---

acceptance/Gemfile

Update the beaker gem version used in acceptance to beaker 3.1.0 to allow
for MacOS Sierra (10.12) testing.

(PCP-614) Update beaker version to 3.1.0

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb

run_puppet_twice.rb continues to pass even when the pxp-module-puppet script
does not actually handle re-running Puppet (i.e. if a stable packages is accidentally used).
This is due to a race where the test case end the 1st puppet run
before the 2nd puppet run has had time to launch puppet and detect that puppet is
already running.
This commit ensures that the 2nd puppet run has exited before continuing and
ending the 1st puppet run.
[skip ci]

(PCP-611) Ensure run_puppet_twice.rb fails when appropriate

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb

Reverts puppetlabs/pxp-agent#498
It fails consistently on Ubuntu 14.04, and is currently blocking a release.

Revert "(PCP-611) Ensure run_puppet_twice.rb fails when appropriate"

---

acceptance/setup/common/005_SyncTime.rb

When testing a 32-bit puppet-agent MSI on Windows Server 2016, forcing a
time sync through beaker was causing the host to temporarily have a time
far in the past. This was preventing retrieval of the signed SSL
certificate from the master. However, the host appears to sync correctly
on its own, so this commit causes beaker to skip forcing a sync.

(PCP-625) Skip beaker time sync on Windows Sever 2016

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/aio/pre-suite/010_Install.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb

Re-introduce the update to run_puppet_twice.rb that was failing on Ubuntu 14.04.
Adds a commit that fixes the issue with Ubuntu 14.04 - this turned out to be PA-654 where puppet was running as a service after installing puppet-agent. This commit ensures puppet service is stopped and disabled.
[skip ci]

(PA-654)(PCP-611) Ensure puppet service is not running during acceptance

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/aio/pre-suite/010_Install.rb

The code committed for PCP-611 fails in CI on some platforms. 
On OSX, the puppet service may be running in spite of the pre-suite stopping it. I believe this is expected behaviour on OSX, it will start up installed services it finds in a stopped state. This PR adds an extra pre-suite step to not have puppet agent daemonized; so it will not run and interfere with tests even if the service re-enables.
Additionally the test failed on Solaris because the helper method used the -e option that is not supported on Solaris' version of grep. This option is actually redundant on the platforms that do support it (as the argument to grep is a literal string and not an expression), so this PR simply removes it.
[skip ci]

(PCP-611) Acceptance fixes for run_puppet_twice.rb

---

CMakeLists.txt
locales/pxp-agent.pot

This bumps the version of pxp-agent to 1.3.1 following the release of
1.3.0 as part of puppet-agent 1.8.0.

(PA-652) Bump pxp-agent version to 1.3.1

---

acceptance/tests/restart_host_run_puppet.rb

The beaker restart helper sends shutdown to Windows, but then hangs for
a long timeout as ssh doesn't close cleanly. This is filed as BKR-971.
As a work-around, add a 5s timeout after sending shutdown to allow it be
begin, then close the SSH connection and start attempting to reconnect.

(PCP-631) Prevent hanging on Windows ssh after shutdown

---

.gitignore
acceptance/.gitignore
acceptance/setup/common/005_SyncTime.rb

Previously we skipped timesync on Windows Server 2016 in commit cd33472
However Windows 10 shares the same kernel and requires a similar fix.  This
commit adds a Windows 10 exclusion for the beaker timesync process.
[skip ci]

(PCP-625) Skip beaker time sync on Windows 10

---

acceptance/setup/common/050_Setup_Broker.rb

Pins pcp-broker to a specific version (0.8.4) during acceptance testing
to ensure reproducible tests and avoid breakage due to development on
pcp-broker.

(PCP-650) Pin pcp-broker to 0.8.4 in tests

---

modules/spec/unit/modules/puppet_spec.rb

Ensure that pxp-module-puppet works if Puppet's output contains potentially syntax significant characters.

(PCP-592) pxp-module-puppet spec test for syntax chars

---

acceptance/Gemfile
acceptance/tests/restart_host_run_puppet.rb

Beaker 3.6.0 includes a fix for BKR-1006, which updates the Windows
reboot helper to close the SSH connection immediately. This avoids long
timeouts on the connection.
Also reverts a previous hack to try to work around the Beaker issue.

(PCP-631) Use Beaker 3.6.0 for fix to reboot

---

acceptance/lib/pxp-agent/test_helper.rb

pcp-broker 1.0 will include breaking changes for PCP v1 clients, notably
that association requests are deprecated. They'll only be supported for
the agent type without modification; other types can be used if that
type is also appended to the connection URI (the type used for
connection URI and association request must match).

(PCP-645) Append client_type to URI for pcp-broker 1.0 compatibility

---

lib/inc/pxp-agent/agent.hpp
lib/inc/pxp-agent/configuration.hpp
lib/src/agent.cc
lib/src/configuration.cc

Adds a hidden option that can be used to configure the websocket ping
interval from the default of 15 seconds.

(PCP-469) Add hidden option for configuring ping interval

---

.travis_target.sh
CMakeLists.txt
README.md
appveyor.yml
lib/CMakeLists.txt
lib/inc/pxp-agent/agent.hpp
lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/module.hpp
lib/inc/pxp-agent/pxp_connector.hpp
lib/inc/pxp-agent/pxp_connector_v1.hpp
lib/inc/pxp-agent/pxp_connector_v2.hpp
lib/src/agent.cc
lib/src/configuration.cc
lib/src/pxp_connector_v1.cc
lib/src/pxp_connector_v2.cc
lib/tests/CMakeLists.txt
lib/tests/common/mock_connector.cc
lib/tests/common/mock_connector.hpp
lib/tests/component/external_modules_interface_test.cc
lib/tests/unit/agent_test.cc
lib/tests/unit/configuration_test.cc
lib/tests/unit/pxp_connector_v1_test.cc
lib/tests/unit/pxp_connector_v2_test.cc
lib/tests/unit/request_processor_test.cc
locales/pxp-agent.pot

Adds a connector for PCP version 2 while retaining a PCP version
1-compatible connector as well. Adds `pcp-version` option to select
between `1` and `2`.
Depends on https://github.com/puppetlabs/cpp-pcp-client/pull/211.

(PCP-647) Add PCP version 2 connector and allow configuring it

---

acceptance/README.md
acceptance/lib/pxp-agent/config_helper.rb
acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/common/050_Setup_Broker.rb

Enable configuration of PCP version for testing, and use PCP v2 by default.
Blocked on https://github.com/puppetlabs/pxp-agent/pull/531.

(PCP-661) Test using PCP v2 by default

---

CMakeLists.txt

For the upcoming puppet-agent 1.7.2 release

(PCP-686) Bump version of pxp-agent to 1.2.3

---

acceptance/tests/pxp-module-puppet/run_puppet_v1.rb

Adds a test case that verifies sending and receiving messages over a PCP
v1 connection.
[skip ci]

(PCP-660) Add test case for connecting to a PCP v1 endpoint

---

lib/src/modules/ping.cc
lib/tests/unit/modules/ping_test.cc
locales/pxp-agent.pot

If no debug chunks are included, ping will respond with an empty
"request_hops" entry.

(PCP-676) Remove ping dependency on debug chunks

---

acceptance/lib/pxp-agent/test_helper.rb

Replace occurrences of puts or prints with logger entries.
Also improves the message output when get_pcp_broker_status fails to connect, to hint that it is expected if the broker is still starting up.
[skip ci]

(PCP-365) Acceptance should not use puts or prints

---

CMakeLists.txt

This commit updates pxp-agent's version to 1.3.3 following the release
of 1.3.2 as part of puppet-agent 1.8.3

(packaging) Bump version to 1.3.3

---

acceptance/lib/pxp-agent/test_helper.rb

acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb fails on
slower hosts, where our helper allows 30 seconds (15 retries at 2 second interval) for
a sleep process to appear on agent, but the process takes longer to appear.
This commit increases the allowed time to 120 (120 retries at 1 second interval) to
allow substantially more time for sleep to be running.
Also changed the timeout behavior to raise() instead of fail() so that the calling test
gets a Error result instead of a Failed result.
[skip ci]

(PCP-615) Acceptance - allow longer wait for sleep process on agent

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/rerun_transaction.rb
lib/src/request_processor.cc
lib/tests/component/external_modules_interface_test.cc
locales/pxp-agent.pot

Changes the behavior of a duplicate nonblocking request to send a
provisional response instead of a pxp error.
Previously we checked to make sure the transaction ID was not
currently in a thread. This commit checks the on disk storage as well
in case the agent has restarted.

(PCP-627) Send provisional response for conflicting transaction-id

---

acceptance/Rakefile
acceptance/config/aio/options.rb
acceptance/setup/common/022_Remove_LD_PRELOAD.rb
acceptance/tests/restart_host_run_puppet.rb

As in Facter, we have to unset LD_PRELOAD. Leaving it set results in
`errno` being set to non-zero at the start of execution.
This depends on https://github.com/puppetlabs/pl-build-tools-vanagon/pull/9 being merged and new packages built.

(PCP-612) Re-enable Cisco IOS XR platform

---

lib/src/external_module.cc

Unify the formatting of the `leatherman::execution::execute` calls in the project.

(maint) Unify code style

---

acceptance/setup/common/050_Setup_Broker.rb

Updates acceptance tests to operate against pcp-broker#master. This
helps catch compatibility failures between client and master.

(maint) Reset acceptance to use pcp-broker#master

---

acceptance/config/aio/options.rb
acceptance/lib/pxp-agent/test_helper.rb
acceptance/teardown/common/099_Archive_Logs.rb
acceptance/tests/failover/intentional_shutdown_failover.rb
acceptance/tests/failover/timeout_failover.rb
acceptance/tests/invalid_ssl_config.rb
acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb
acceptance/tests/pxp-module-puppet/run_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_agent_disabled.rb
acceptance/tests/pxp-module-puppet/run_puppet_nonASCII.rb
acceptance/tests/pxp-module-puppet/run_puppet_result_changed.rb
acceptance/tests/pxp_agent_associate.rb
acceptance/tests/reconnect_after_broker_unavailable.rb
acceptance/tests/restart_host_run_puppet.rb

@james-stocks what would you suggest for addressing the places we delete log files? It'd be useful to keep most of the logs, so maybe we should use different locations for the tests that want to use a fresh log file.

(PCP-529) Archive logs from acceptance runs

---

acceptance/tests/pxp-module-puppet/run_puppet_during_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
acceptance/tests/pxp-module-puppet/run_puppet_v1.rb

Removes `show_pcp_logs_on_failure` from tests not present on the LTS-1.7
branch.

(PCP-529) Remove show_pcp_logs_on_failure from new tests

---

acceptance/tests/pxp-module-puppet/rerun_transaction.rb
acceptance/tests/pxp-module-puppet/run_puppet_during_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
acceptance/tests/pxp-module-puppet/run_puppet_v1.rb

Merge down from stable, and remove tests from master-only test.

(PCP-529) Remove show_pcp_logs_on_failure from master tests

---

acceptance/tests/failover/timeout_failover.rb
lib/src/configuration.cc

The default ping-interval of 15 seconds, combined with
allowed-keepalive-timeouts of 2, means that if the pcp-broker is
overloaded for more than 45 seconds the agent will disconnect and
reconnect. This can happen when several thousand agents attempt to
connect at once, causing reconnection to spiral out of control.
The ping only has 2 functions: prevent the server from disconnecting the
agent (currently the server has a 15 minute timeout) and detect if the
server has become unavailable without closing the TCP connection
cleanly. This 2nd one doesn't need to happen on such a quick interval.
Change the default ping-interval to 3 minutes to reduce chances of
disconnecting under startup load.

(PCP-729) Change default ping-interval to 3 minutes

---

acceptance/tests/failover/timeout_failover.rb
lib/src/configuration.cc

Reverts puppetlabs/pxp-agent#564
This change is substantial, and affects tests more than I thought. We also need to do it in PE. I'm probably more comfortable reverting this for now and only changing it in PE in a configurable way.

Revert "(PCP-729) Change default ping-interval to 3 minutes"

---

acceptance/setup/common/050_Setup_Broker.rb

This will prevent breaking tests during a release.

(maint) Pin pcp-broker to latest release

---

acceptance/tests/pxp-module-puppet/run_puppet_nonASCII.rb

On Windows Server 2008, powershell will hang waiting for input. Skip
using powershell and run wmic directly.

(maint) Fix skipping for Windows Server 2008

---

acceptance/tests/failover/timeout_failover.rb
lib/src/configuration.cc

With PCP-734 fixed, pxp-agent will attempt to reconnect immediately
unless the broker disappears and the TCP connection is not closed. In
that case, it'll take 4-6 minutes to detect a failure.
This interval is chosen to minimize disconnects under reasonable loads
for pcp-broker, e.g. 10k nodes reconnecting.
Adjust the hard failover test to use a short ping-interval to minimize
test time.

(PCP-729) Change default ping-interval to 2 minutes

---

acceptance/lib/pxp-agent/test_helper.rb

Previously only the last broker log would be preserved, as every
re-invocation of pcp-broker would overwrite the previous log. Now use a
uuid to ensure each log is unique.

(maint) Ensure all broker logs are unique so they can be preserved

---

acceptance/tests/pxp-module-puppet/run_puppet_umask.rb

The `run_puppet_umask` test was executing `/bin/touch` which was failing on Macs as the `touch` command lives in `/usr/bin/touch` there.

(PCP-736) Fix test on Mac OS

---

acceptance/tests/pxp-module-puppet/run_puppet_umask.rb

Ideally we'd set umask on the service and verify it had changed, but
doing that on AIX looks non-trivial if its even possible. It also
wouldn't bring much extra testing, so for now just verify that the
default umask is used.
[skip ci]

(PCP-740) Check for default umask on AIX service

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Previously, we returned on the transaction_uuid of the report and relied
on orchestrator to use that to retrieve metrics about what happened.
Because the report may not necessarily have been stored in PuppetDB by
the time that data was looked up, orchestrator could fail to find
metrics immediately after the run finished. To get around that, we now
return the metrics as part of the result, rather than requiring it to
separately query the data we already have.

(PCP-742) Return metrics with pxp-module-puppet result

---

ext/solaris/smf/pxp-agent.xml

Prior to this commit, the svcs -xv command would
return a libscf error when encountering the unset
name field in the manpage property for pxp-agent.
This commit adds a string to that setting to bring
it into alignment with other Puppet services.

(PCP-745) Add manpage name to Solaris SMF manifest

---

acceptance/tests/pxp-module-puppet/run_puppet_nonASCII.rb

We incorrectly pass a block that accepts a single argument to
`each_with_index`. This somehow works, but I wouldn't necessarily expect
it to work in a future version of Ruby. Fix to use `each`.

(maint) Fix unnecessary use of each_with_index

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

In order to track the execution of a job all the way through the agent to
PuppetDB, we now have a --job-id flag that can be passed to `puppet agent`.
That flag will cause the provided job id to be added to the report that
gets stored in PuppetDB, making it easy to determine whether a report was
associated with a job.
We now optionally accept a "job-id" input to pxp-module-puppet and will
pass that along to the agent. This is provided as a top-level input rather
than a flag for backward compatibility (so old agents will ignore the
option rather than fail), and because it properly represents metadata about
the run rather than being an ordinary flag.
This PR also includes a substantial refactor of pxp-module-puppet and its
tests, turning the code into a class rather than leaving everything …

(PCP-699) Accept and pass job-id in pxp-module-puppet

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Because of the circuitous route to which the final version of this code was
arrived, as well as unit test coverage lacking at the outer levels, there are a
couple of places where arguments aren't properly set/used on the ModulePuppet
instance. This PR fixes those and improves the test coverage to exercise as
much of the module as possible.

(PCP-699) Avoid undefined variables when running puppet

---

acceptance/setup/aio/010_Install.rb

This commit adds the ability to specify SERVER_VERSION=latest when running
pxp-agent tests to test against server latest packages from nightlies.
Sanity checks are added to ensure that if SERVER_VERSION or SHA are set to
latest, download URLs are set correctly to pull from nightlies

(PCP-748) Add the ability to test against puppetserver latest

---

exe/CMakeLists.txt

Versioning the executable files clutters the filesystem and,
more importantly, totally breaks service management on SLES.
Since we don't have any use for symlinks to versioned binaries,
we should just get rid of them.

(packaging) Do not use versioned executable

---

ext/suse/pxp-agent.init

From pxp-agent 1.5.3 to 1.6.0, pxp-agent used a versioned binary with
pxp-agent symlinked to it. When upgrading, the binary used to start the
pxp-agent service would change. On SUSE, this prevented restarting the
service after upgrade because checkproc would not detect the existing
process (needed by condrestart) and killproc would not kill the process
started with the previous binary. Use pgrep/kill instead - with
appropriate guards to check it was the expected service process - to
ensure we can restart the service after upgrading from one of those
versions.
[skip ci]

(PCP-755) Support restarting service when the binary path changes

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/run_puppet_exec.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb

PE-14681 and MODULES-3125 identified issues running commands via Puppet
exec from other service agents. These issues led to PUP-6675: selinux
prevents processes from writing to files in /tmp if they don't have a
reason to do so. The Puppet service selinux policy appears to exempt
this, but other services that invoke Puppet - such as pxp-agent - aren't
configured that way and cause silent exec failures.
PUP-6675 fixes this issue. We add an acceptance test to ensure that it
doesn't recur in pxp-agent.

(maint) Add testing around exec via Puppet

---

exe/main.cc
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
locales/pxp-agent.pot

Logs pxp-agent version and configured log level as soon as logging is
configured. Clarifies when versions change in logging, which makes
debugging issues easier.

(maint) Log version and level at startup

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/aio/010_Install.rb
acceptance/setup/common/050_Setup_Broker.rb

This commit updates the acceptance install pre-suite to allow installing
an ec2 master dynamically on a el based system without intervention.
Due to the expectations of the nightly puppetserver repo, the nightly
puppet-agent is installed first and then over-written with the
puppet-agent version under test. The specification of a SERVER_VERSION
is also supported.
A `LEIN_PROFILE` constant has been added to switch between profiles
based on whether the SUT has access to the `puppetlabs.net` network
or not to enable the installation of pcp-broker on the master.

(PCP-759) Enable EC2 master install

---

acceptance/tests/pxp-module-puppet/run_puppet_exec.rb

Cygwin is installed at C:/cygwin, not C:/cygwin32.
[skip ci]

(maint) Fix the test on win-10-ent-i386

---

acceptance/config/aio/options.rb
acceptance/lib/pxp-agent/test_helper.rb

Configure beaker with debug logging, and ensure pcp-client logging goes
to stdout. This is to make it easier to debug connectivity issues.
[skip ci]

(maint) Use debug logging in acceptance tests

---

acceptance/lib/pxp-agent/test_helper.rb

Ensure failed attemption connects are closed. If not done, we can end up
with multiple connections, and an earlier attempt can supersede a later
one. When that happens, the connection being used for testing will fail
to receive expected responses.
[skip ci]

(PCP-750) Ensure failed connection attempts are closed

---

ext/debian/pxp-agent.init
ext/redhat/pxp-agent.init
ext/suse/pxp-agent.init

The init scripts used to run pxp-agent as a service currently ensure the
rundir exists before starting. Update them to also ensure the logdir
location exists, in case it's volatile.

(PCP-697) Ensure default log location exists on startup

---

appveyor.yml
exe/task.cc
exe/task.hpp
exe/tests/fixtures.hpp
exe/tests/main.cc
locales/pxp-agent.pot

Accepts file extensions on non-Windows platforms, except the reserved extensions `.json` or `.md`. That allows writing cross-platform tasks in scripting languages.
Adds support for cross-platform scripts via powershell and ruby.

(PCP-758) Support file exts on non-Windows, powershell/ruby on Windows

---

acceptance/lib/pxp-agent/task_helper.rb
acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/tasks/run_echo.rb
acceptance/tests/tasks/run_ps1.rb
acceptance/tests/tasks/run_puppet.rb
acceptance/tests/tasks/run_ruby.rb
exe/task.cc

Adds acceptance tests that exercise a basic shell task, a powershell
task on Windows, and ruby and puppet tasks.
Refactors code to check puppet results for re-use in run_task.
Task runner now accepts a `trace` argument to aid in debugging. Passing
it will cause logging to be configured to the `trace` level, so issues
can be dubugged locally using `cat input.json | task trace`.

(PCP-758) Add tests for shell, powershell, ruby, and puppet tasks

---

acceptance/tests/tasks/run_puppet.rb
acceptance/tests/tasks/run_ruby.rb

The shebang scripts didn't work on all platforms. Fix for MacOS, RedHat
5, Solaris 10, and Arista.

(PCP-758) Fix acceptance tests

---

CHANGELOG.md
CMakeLists.txt
locales/pxp-agent.pot

This updates the version numbers and changelog for the 1.5.4 release, in
preparation for the puppet-agent 1.10.5 release.

(packaging) Prepare for 1.5.4 release

---

acceptance/tests/tasks/run_puppet.rb

AIX and Solaris 11 have similar shebang behavior to el-5 and Solaris 10.
Update test special casing for running a puppet manifest to include
them.
[skip ci]

(maint) Update puppet task test for hardware platforms

---

CMakeLists.txt

Enable nxcompat and dynamicbase flags in Windows builds of pxp-agent.
Being done to meet some customer's security audit requirements.

(PCP-775) Enable DEP support in Windows version of PCP/PXP binaries

---

acceptance/README.md
acceptance/setup/aio/010_Install.rb

Enables running acceptance from a local package. Only the agent uses the
specified package, master will still rely on SHA/SUITE_VERSION.

(maint) Enable acceptance from local package

---

acceptance/lib/pxp-agent/test_helper.rb
lib/src/request_processor.cc

During a non-blocking request, if a status query is recieved after
sending the provisional response but before the action thread starts a
subprocess and writes the PID file it will report status "unknown". In
PCP-767, we'll be adding a new module that downloads a file before
starting a subprocess; if that download takes awhile, we would be in an
"unknown" state for an inappropriate amount of time.
Report "running" if the action thread is still active rather than
"unknown", as we know the action is still running.

(PCP-633) Report running if action thread is still active

---

acceptance/tests/pxp-module-puppet/run_puppet_agent_disabled.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
modules/pxp-module-puppet

When output is UTF-8, but running on a Japanese-configured system with
Windows-31J, we get UndefinedConversionError trying to convert the
encoding to UTF-8. Handle this error.
Disable tests that fail with Japanese locales now that Puppet is
translated into Japanese. This should be reverted once PCP-776 is fixed.

(maint) Unblock acceptance tests on Japanese locale instances

---

exe/task_wrapper.cc
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/external_module.cc
lib/src/modules/task.cc
lib/src/results_storage.cc

The code looks bad, linting doesn't like it, and it should have no effect.
If pxp-agent is invoked by finding it on PATH, finding the task_wrapper would search on the current working directory and likely fail. Fix so if pxp-agent was found via PATH, task_wrapper will also be searched via PATH.

(maint) Drop ifdefs for linting, fix finding task_wrapper via PATH

---

acceptance/tests/pxp-module-puppet/run_puppet_agent_disabled.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

`pxp-module-puppet` can't detect that a run failed - because Puppet was
disabled or because Puppet was already running - when Puppet's output is
translated. What we currently try to do is
- if Puppet's disabled, return an error message to that effect
- if Puppet's running, wait until it stops and start a new run
Switch to checking for the lockfiles that Puppet uses to determine
disabled or running, rather than parsing the output. This makes the
implementation language-agnostic.

(PCP-776) Detect disabled/running Puppet via lock files

---

exe/task_wrapper.cc
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/external_module.cc
lib/src/modules/task.cc
lib/src/results_storage.cc
lib/tests/unit/configuration_test.cc

Boost.Filesystem's permission behaves strangely on Windows. It seems to
set read-only when it shouldn't (according to documentation). Avoid
using it to set permissions on Windows; we want it to be a noop anyway.

(maint) Avoid setting permissions on Windows

---

lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/module.hpp
lib/inc/pxp-agent/pxp_connector.hpp
lib/src/module.cc
lib/src/modules/task.cc
lib/tests/component/external_modules_interface_test.cc
lib/tests/unit/agent_test.cc
lib/tests/unit/modules/ping_test.cc
lib/tests/unit/modules/task_test.cc

Apply fixes suggested by the Eclipse CDT IDE:
* define virtual destructors for classes which are deleted through base class typed pointers
* catch exceptions by reference
* remove unused variables

(maint) IDE suggested fixes

---

lib/src/modules/task.cc
lib/tests/resources/tasks-cache/823c013467ce03b12dbe005757a6c842894373e8bcfb0cf879329afb5abcd543/multi
lib/tests/resources/tasks-cache/88a07e5b672aa44a91aa7d63e22c91510af5d4707e12f75e0d5de2dfdbde1dec/multi.bat
lib/tests/unit/modules/task_test.cc
locales/pxp-agent.pot

Support `stdin` and `environment` options for `input_method`.
Supports ORCH-1956.

(maint) Support `input_method` on tasks

---

lib/src/modules/task.cc

For unknown reasons, using Boost.Filesystem's permissions to apply
executable permissions on Solaris is failing. This manifests as files
with all permissions removed.
The work this impacts is blocking many other things, so use a very
targetted fix while we figure out what's going on. Use chmod directly to
fix permissions that aren't applied correctly via Boost.

(PCP-769) Fix permissions on Solaris

---

lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc
lib/src/external_module.cc
lib/src/modules/task.cc
lib/src/results_storage.cc
lib/tests/unit/configuration_test.cc
lib/tests/unit/modules/task_test.cc

Applying permissions on Windows and using fs::permissions on Solaris
were both hacked around due to a faulty assumption that they were broken
on those platforms. The root cause of both issues was a static
initialization ordering issue.
Fix it by using a macro to alias the variable name, rather than
assigning from a global variable in another object. Unwind Windows and
Solaris hacks.

(PCP-769) Fix permissions hacks

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb
acceptance/tests/pxp-module-puppet/run_puppet_during_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb

On our AIX 7.1 machines, there's a pre-existing sleep process that's
constantly renewed. Make the check for the sleep process we expect from
Puppet more specific, so we don't falsely identify the wrong one.
[skip ci]

(PCP-783) Specify required sleep process more thoroughly

---

lib/src/modules/task.cc
lib/tests/unit/modules/task_test.cc
locales/pxp-agent.pot

In the task response, return exitcode and stderr as well as stdout. This
allows a consumer to skip querying status, as all the data they need for
a task is in the response.
The status query used to retrieve task results returns stdout, stderr,
and exitcode. This makes the response to running a task - which is
returned immediately upon completion, rather than in response to a
status request - contain the same information so a controller can avoid
a follow-up request to get it.

(maint) Update task blocking response to return all results

---

lib/src/modules/task.cc

Prevent possible memory leak of the OpenSSL's `env_md_ctx_st` structure which could happen in the `calculateSha256` function in case of an IO error.
While at it use the `boost::algorithm::hex` function for turning the digest's binary form into a hex string instead of a custom implementation.

(maint) Prevent possible leak of env_md_ctx_st struct

---

modules/pxp-module-puppet

Restrict permissions on output from pxp-module-puppet to 0640, to
prevent it being world-readable.

(PCP-766) Restrict contents of spool-dir from pxp-module-puppet

---

lib/src/modules/task.cc
locales/pxp-agent.pot

This was accidentaly carried over from external modules implementation
and shouldn't be needed. We want to use whatever exit code is returned
from task_wrapper.

(maint) Remove unneeded "error handling" on exit code 5

---

acceptance/lib/pxp-agent/config_helper.rb
acceptance/lib/pxp-agent/test_helper.rb

When an action finishes, it always returns an exitcode. stdout and
stderr are only included if they have contents. Identify completion by
the presence of exitcode so we can finish early, rather than timing out
if a failure means stdout is empty.
Also include debug logging when Beaker is configured to use debug
output.
[skip ci]

(maint) Improve test debugibility and failure handling

---

lib/src/action_response.cc
lib/tests/CMakeLists.txt
lib/tests/unit/action_response_test.cc

If an execution error is found in the metadata of a non-blocking action,
send a response with `{"_error": {"kind":
"puppetlabs.pxp-agent/task-error", "msg": <msg>, "details" {}}}` on
stdout. This should only happen if an error occurs while invoking an
action that would result in sending an `rpc_error_message`, and is done
to make sure the same error message can be retrieved by a status request
if the `rpc_error_message` is lost.

(PCP-786) Send error response to status if found

---

acceptance/tests/tasks/task_download.rb

Fixes task_download's permission check on Windows. Somehow this slipped
through prior ad-hoc testing. Also fix running the task_download task
standalone.
[skip ci]

(PCP-771) Fix task_download task on Windows

---

appveyor.yml

Appveyor appears to work despite not explicitly installing zlib (needed
by libcurl). Presumably it has its own. Install our zlib anyway to avoid
future issues if that changes.

(maint) Add missing libcurl dependency to Appveyor builds

---

acceptance/files/complex-args.json
acceptance/files/complex-output
acceptance/files/complex-task.ps1
acceptance/lib/pxp-agent/task_helper.rb
acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/tasks/run_ps1.rb
appveyor.yml
exe/CMakeLists.txt
exe/PowershellShim-Helper.ps1
exe/PowershellShim.ps1
exe/README.md
exe/powershell_shim.ps1
exe/tests/PowershellShim.Tests.ps1
lib/inc/pxp-agent/modules/task.hpp
lib/src/modules/task.cc

By default invokes .ps1 files (and any that request input_method: powershell) with a shim that parses JSON into named params. Includes acceptance tests.

(PCP-789) Add input_method: powershell for .ps1 files

---

acceptance/files/complex-args.json
acceptance/files/complex-output
acceptance/files/complex-task.ps1
acceptance/tests/tasks/run_ps1.rb

This varies a lot across platforms and locales, and is marginally
interesting. Remove from testing rather than add more complex handling
of it.
[skip ci]

(PCP-789) Remove DateTime from testing

---

acceptance/Rakefile
acceptance/setup/aio/010_Install.rb

Test setup depends on a local tmp dir existing. We create it when
generating a hosts file, and used to create it when installing the
puppet-agent package. We no longer create it for install, but still use
it for testing and the hosts file. Ensure it's always created in the
Rakefile so it's available during setup.

(maint) Fix local tmp dir creation

---

acceptance/teardown/common/099_Archive_Logs.rb

On Cisco NX we don't login as root. However, pxp-agent runs as root and
restricts permissions on the logdir to root owner and group.
Ensure logdir is readable by login user before attempting to copy it
back.

(maint) Fix acceptance teardown on Cisco NX

---

CMakeLists.txt

If cpp-hocon is built with Boost.Locale support, we need to also use
the locale library when linking it.

(PCP-511) Include locale for cpp-hocon

---

lib/CMakeLists.txt

libpxp-agent now uses libcpp-hocon, which introduces a dependency on
Boost.Locale. On macOS that requires linking iconv. Include it as a
public dependency of libpxp-agent so it's incorporated into binaries
that link against it (pxp-agent and pxp-agent-unittests).

(PCP-511) Add iconv dependency for libpxp-agent

---

lib/src/configuration.cc
locales/pxp-agent.pot

Paths for non-root pxp-agent in puppet-specifications differ because the
original implementation of this wasn't consistent with patterns used for
Facter and Puppet. Make the defaults consistent with
puppet-specifications.

(PCP-792) Update non-root paths to be consistent with spec

---

acceptance/tests/restart_host_run_puppet.rb

We've gone through several fedora releases, and made some fixes to make
pxp-agent tests more reliable. Enable the test and see how they do.
[skip ci]

(PCP-585) Re-enable restart test on Fedora

---

lib/inc/pxp-agent/configuration.hpp

Previously members of EntryBase would not be correcty destructed when an
Entry is destroyed. Add a virtual destructor to ensure that happens.

(maint) Ensure EntryBase is correctly destroyed

---

lib/tests/resources/config/bad-broker.conf
lib/tests/resources/config/bad-master.conf
lib/tests/resources/config/duplicate.conf
lib/tests/resources/config/multi-broker.conf

Take advantage of the recently added support for using the HOCON syntax in the configuration files in the configuration files used in unit test.

(PCP-511) Use HOCON configuration syntax

---

acceptance/lib/pxp-agent/config_helper.rb
acceptance/lib/pxp-agent/task_helper.rb
acceptance/tests/failover/intentional_shutdown_failover.rb
acceptance/tests/failover/timeout_failover.rb
acceptance/tests/invalid_ssl_config.rb
acceptance/tests/multiple_pxp_agent_daemon.rb
acceptance/tests/pxp-module-puppet/negative/attempt_puppet_flag_whitelist_bypass.rb
acceptance/tests/pxp-module-puppet/rerun_transaction.rb
acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb
acceptance/tests/pxp-module-puppet/run_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_agent_disabled.rb
acceptance/tests/pxp-module-puppet/run_puppet_during_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_exec.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb
acceptance/tests/pxp-module-puppet/run_puppet_nonASCII.rb
acceptance/tests/pxp-module-puppet/run_puppet_result_changed.rb
acceptance/tests/pxp-module-puppet/run_puppet_result_failed.rb
acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
acceptance/tests/pxp-module-puppet/run_puppet_umask.rb
acceptance/tests/pxp-module-puppet/run_puppet_v1.rb
acceptance/tests/pxp_agent_associate.rb
acceptance/tests/reconnect_after_broker_unavailable.rb
acceptance/tests/restart_host_run_puppet.rb
acceptance/tests/service_stop_start.rb
acceptance/tests/tasks/run_echo.rb
acceptance/tests/tasks/run_ps1.rb
acceptance/tests/tasks/run_puppet.rb
acceptance/tests/tasks/run_ruby.rb
acceptance/tests/tasks/task_download.rb

Update acceptance tests to use HOCON syntax when generating pxp-agent's config file.

(PCP-511) Generate HOCON config file

---

acceptance/tests/pxp-module-puppet/run_puppet_agent_non_root.rb

- Address failures on solaris and OSX
- Address test hang on debian 7 redhat 5 redhat 6 ubuntu 14.04

(PCP-792) test for pcp as non root agent

---

acceptance/setup/common/050_Setup_Broker.rb

(maint) Pin lein to 2.7.1

---

lib/src/modules/task.cc
lib/tests/unit/modules/task_test.cc

Ensure the tasks cache directory is recreated every time we try to use
it. If it's deleted, we now recreate it before trying to download a
task.

(PCP-791) Ensure tasks cache directory is recreated

---

README.md
lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/external_module.hpp
lib/inc/pxp-agent/modules/task.hpp
lib/inc/pxp-agent/request_processor.hpp
lib/inc/pxp-agent/results_storage.hpp
lib/inc/pxp-agent/time.hpp
lib/inc/pxp-agent/util/purgeable.hpp
lib/src/configuration.cc
lib/src/external_module.cc
lib/src/modules/task.cc
lib/src/pxp_connector_v1.cc
lib/src/request_processor.cc
lib/src/results_storage.cc
lib/src/thread_container.cc
lib/src/time.cc
lib/tests/common/mock_connector.hpp
lib/tests/component/external_modules_interface_test.cc
lib/tests/unit/agent_test.cc
lib/tests/unit/configuration_test.cc
lib/tests/unit/external_module_test.cc
lib/tests/unit/modules/task_test.cc
lib/tests/unit/results_storage_test.cc
locales/pxp-agent.pot

Refactor code to reduce duplication, fix error message. Update README to include task-cache-dir. Switch to format_n for pluralization.
Switch to using min of 1h or spool-dir-purge-ttl. Add task-cache-dir-purge-ttl configuration option.
Purge cached tasks older than task-cache-dir-purge-ttl using a thread similar to spool dir purging. The purging thread uses a mutex to check for shutdown.
A separate mutex is used to ensure a directory is not purged while it is also being used - i.e. ensuring the cache directory exists and has an updated last modified time happens under the mutex. After the mutex releases, purge should be prevented by the updated last modified time. The mutex will block downloading tasks, so it's acquired only while creating+updating the directory or checking+deleting it.

(PCP-809) Purge old cached tasks

---

acceptance/lib/pxp-agent/test_helper.rb

The default shell on Solaris 10 (SPARC) doesn't support `kill -s TERM`,
so use `kill -15` instead. This is more consistent with other `kill`
calls used in acceptance tests as well.
[skip ci]

(PCP-801) Use kill -15 rather than kill -s TERM for broader support

---

acceptance/tests/tasks/task_download.rb

Removes the 404 response body check from the task_download acceptance
tests, so that they don't fail when the body text generated by the
server has been updated.
We saw this happen in an [experimental build](https://jenkins-cinext.delivery.puppetlabs.net/job/experimental_puppet-agent_intn-van-sys_suite-daily-pxp-agent-opswork-1.10.x/SLAVE_LABEL=beaker,TEST_TARGET=amazon6-64a/1/testReport/) today - it seems beyond the scope of these tests to validate the response body from the server.

(maint) Make task download 404 test more flexible

---

exe/PowershellShim-Helper.ps1
exe/tests/PowershellShim.Tests.ps1

The powershell shim for using the powershell input method for tasks
requires .NET Framework 3.5. This is a new dependency for pxp-agent, but
isn't required for all functionality. Add a useful error to help users
configure their systems correctly if they want to use the powershell
input method.

(PCP-826) Add helpful error message if .NET assemblies are not found

---

acceptance/setup/aio/010_Install.rb

This commit changes the name of the nightlies server to the actual hostname so that when we remove the 'nightlies' cname (to use for *new* nightlies), tests won't break. THIS SHOULD NOT BE PERMANENT (see RE-10231).

(RE-9880) Update acceptance tests that reference nightlies

---

ext/systemd/pxp-agent.logrotate

Previously pxp-agent log rotation didn't complete correctly. It would
rotate the log file, but fail to signal the service because the if
statement was testing the output, not the exit code. Simplify the test
by using is-active and signal the service based on exit code.

(PCP-834) Fix pxp-agent log rotation

---

acceptance/config/aio/options.rb

Prior to this commit, pxp-agent acceptance is failing in setup
following the removal of the "puppet master" subcommand.
This commit updates the acceptance configuration options so we use
service scripts to start/stop puppetserver services.

(maint) Acceptance: Use service scripts to start puppetserver

---

acceptance/tests/proxy_connection.rb

Amazon test targets not configured to allow proxy connection. Skip.

(maint) Skip amazon targets for proxy_connection

---

acceptance/lib/pxp-agent/task_helper.rb
acceptance/tests/proxy_connection.rb
acceptance/tests/tasks/run_echo.rb
acceptance/tests/tasks/run_ps1.rb
acceptance/tests/tasks/run_puppet.rb
acceptance/tests/tasks/run_ruby.rb
acceptance/tests/tasks/task_download.rb
acceptance/tests/tasks/task_implementations.rb
acceptance/tests/tasks/task_purged_from_cache.rb
lib/inc/pxp-agent/modules/task.hpp
lib/src/modules/task.cc
lib/tests/unit/modules/task_test.cc
locales/pxp-agent.pot

Select implementation that matches known features, initially only `puppet-agent`. Uses first file in `files` if no implementations are provided. Errors if implementations are provided but features do not satisfy any of their requirements.

(PCP-835) Add support for task implementations

---

acceptance/tests/tasks/run_ruby.rb
exe/PowershellShim.ps1
exe/tests/Echo.ps1
exe/tests/PowershellShim.Tests.ps1
lib/src/modules/task.cc
lib/tests/unit/modules/task_test.cc

This metaparameter allows a single executable to be used to provide many
tasks, enabling easier code reuse between similar tasks.
This also updates the Powershell shim to only pass along parameters which are understood by the task, to avoid failing when a task doesn't expect the new implicit *_task* parameter.

(PCP-849) Set _task metaparameter to the task name

---

acceptance/lib/pxp-agent/config_helper.rb
acceptance/tests/validate_file_paths.rb
lib/src/configuration.cc

This updates paths for Windows so that they match new installation paths in puppet-agent 6. 
The puppet-specifications PR for these new paths is here: https://github.com/puppetlabs/puppet-specifications/pull/123. These changes shouldn't be merged until that PR is merged.
These changes should be merged at the same time as the changes that require them in puppet-agent, here: https://github.com/puppetlabs/puppet-agent/pull/1517.

(PCP-838) Update windows agent install paths

---

acceptance/setup/common/060_Setup_PCP_Client.rb
acceptance/tests/invalid_ssl_config.rb

Puppet 6 is removing `puppet cert`. Update tests to use `puppetserver
ca`. For the `invalid_ssl_config` test, this requires a small change in
implementation to generate the alternate CA on the master and copy certs
around, because it's no longer simple to generate it on each agent.

(PCP-856) Update tests to use 'puppetserver ca'

---

acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb
appveyor.yml

Allow that a status request may be undelivered to pxp-agent immediately
after restarting the service. We've seen some occasions where the
service restarts but pcp-broker doesn't receive a disconnect meaning it
always looks like pxp-agent is connected; that can result in losing a
message and waiting 60 seconds before timing out. Add one retry in case
that happened, consistent with how other tools (such as Orchestrator)
implement resilience against lost connections.

(PCP-857) Allow lost message to restarted service

---

acceptance/tests/service_stop_start.rb

:fail_on_fail is not a supported option of the Beaker DSL's 'on'
method. Use :accept_all_exit_codes instead.

(maint) Replace :fail_on_fail with :accept_all_exit_codes

---

lib/src/request_processor.cc

The boost/math/common_factor_rt header has changed to
boost/integer/common_factor_rt in boost 1.67.0. This commit updates pxp-agent
to reference the new header and namespace

(PA-2055) Update boost math header to 'integer'

---

acceptance/tests/tasks/run_multifile.rb
lib/inc/pxp-agent/results_storage.hpp
lib/src/modules/task.cc
lib/tests/resources/tasks-cache/28dd63928f9e3837e11e36f5af35c09068e4d62b355cf169a873a0cdf30f7c95/init.sh
lib/tests/resources/tasks-cache/83bdf04b798a1c145a6a266eef5c80cf9cbe6a8baf6f61de41aea2bf63a3496c/init.bat
lib/tests/resources/tasks-cache/ea7d652bfe797121a7ac8e3654aacf7d50a9a4665e843669b873995b072d820b/init.bat
lib/tests/unit/modules/task_test.cc

Copy task implementation to its module within installdir (when used) to make it easier to test tasks locally within the context of their module.

(PCP-860) Copy task implementation to installdir

---

acceptance/setup/common/045_SetPuppetServerOnAgents.rb
acceptance/setup/common/060_Setup_PCP_Client.rb
acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb

- Specify the `server` setting in puppet.conf to avoid requiring the use
of `--server <server>` in acceptance tests; The puppetserver ca CLI does
not have a `--server` flag like puppet does
- Ensure that the `server` setting is written to the [main] section (not
[agent]) during setup
This is expected to resolve acceptance test failures [like these](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/Acceptance%20Suites/view/6.0.x/view/Suite/job/platform_puppet-agent_puppet-agent-integration-suite_daily-6.0.x/62/), but it must be tested alongside https://github.com/puppetlabs/beaker-puppet/pull/85 -- I'll update once I have an example run.

(maint) Set `server` in puppet.conf in acceptance

---

acceptance/tests/proxy_connection.rb
acceptance/tests/tasks/run_echo.rb
acceptance/tests/tasks/run_ps1.rb
acceptance/tests/tasks/task_purged_from_cache.rb

Fix tests so they work with a mixed set of agents - the default when
running `rake ci:test:aio` - rather than only working when agents are
all windows or all non-windows.

(maint) Fix tests that only worked when agents are all windows or not

---

acceptance/tests/service_stop_start.rb
ext/debian/pxp-agent.init
ext/redhat/pxp-agent.init
ext/suse/pxp-agent.init

This modifies the pxp-agent sysv init script to use `killall pxp-agent` in place of `killproc` when stopping the pxp-agent service. `killproc` did not properly remove all pxp-agent processes, but did remove the pxp-agent pid file, which led to dangling processes that never got cleaned up. This PR also removes logic around using `kill` or `killproc` in the stop function, since it's now not necessary.
Note: the `killall` pattern is copied from sshd.
To reproduce the issue on CentOS 6:
1. Install the puppet-agent
1. Run `pgrep -x pxp-agent` to see the current process id
1. Remove the pxp-agent pid file at `/var/run/puppetlabs/pxp-agent.pid`
1. Restart the pxp-agent service: `service pxp-agent restart`
1. Run `pgrep -x pxp-agent` to see that there are now 2 process ids

(PCP-833) Kill all pxp-agent processes during restart

---

lib/src/request_processor.cc
lib/src/results_storage.cc
lib/tests/component/external_modules_interface_test.cc

Potentially sensitive task execution parameters were being
written to spool-dir. This modifies the way the metadata
is written to enter `"null"` for the "request_params" key.

(PCP-814) Stop writing task execution params to disk

---

exe/tests/main.cc
lib/inc/pxp-agent/external_module.hpp
lib/src/external_module.cc

It looks like certain clang versions are tripping over the switch from `const` to `constexpr`.
Reverts puppetlabs/pxp-agent#747

Revert "(maint) Fixes needed by cppcheck 1.87"

---

.travis.yml
exe/tests/main.cc
lib/CMakeLists.txt
lib/inc/pxp-agent/modules/task.hpp
lib/inc/pxp-agent/util/bolt_module.hpp
lib/inc/pxp-agent/util/utf8.hpp
lib/src/external_module.cc
lib/src/modules/task.cc
lib/src/util/bolt_module.cc
lib/src/util/utf8.cc

In preparation for supporting run_command, upload_file, and run_script over PCP, these changes extract reusable functionality from the existing Task module into a base bolt module class. Future work will introduce other modules that extend this base class.

(PCP-871) Extract a base module class for bolt support

---

acceptance/tests/multiple_pxp_agent_daemon.rb
acceptance/tests/pxp-module-puppet/run_puppet_umask.rb

Due to Fedora removing its 'service' command in release 30, we need to better handle checking the service provider in the acceptance tests.
Previous implementation assumed the 'service' command is always present, however Fedora 30 and future releases will not include this command/package, as Sys-V services are deprecated in favor of systemd.
I tested these changes on a beaker-provisioned Fedora 30 machine and they work as expected.

(PA-2219) Add support for Fedora 30

---

acceptance/tests/tasks/task_download.rb
lib/CMakeLists.txt
lib/inc/pxp-agent/util/bolt_helpers.hpp
lib/src/modules/task.cc
lib/src/util/bolt_helpers.cc

This commit removes functionality for downloading files from the task module
and adds identical functionality to a base utility. The base utility will be
extendable to other modules for use in downloading files
This should unblock work for download_file and run_script modules

(PCP-872) Move download to utility function

---

modules/pxp-module-puppet
modules/spec/unit/modules/puppet_spec.rb

Previously, if a Puppet run was blocked by an in-progress run, it would
wait for the lockfile to disappear, attempt to run, and assume that
the run must have now succeeded.
This behavior was incorrect in multiple cases. First, if multiple runs
queue up, they will all wait for the lock and when it becomes free, one
of them will acquire it and the rest will fail. This case was unhandled,
and the result would indicate that no report was written. That is
technically true, but meaningless as the real issue was that the agent
didn't run.
The other case this could happen is if the lock was in place for more
than ten minutes, at which point the module will trigger a second agent
run attempt regardless, which can fail if the lock is still legitimate.
In both of those cases, the error message …

(PE-26615) Fail gracefully when multiple Puppet runs stack up

---

acceptance/tests/multiple_pxp_agent_daemon.rb
acceptance/tests/pxp-module-puppet/run_puppet_umask.rb

Reverts puppetlabs/pxp-agent#750 since it causes failures:
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/Acceptance%20Suites/view/CI%20Goalie/job/platform_puppet-agent_puppet-agent-integration-suite_daily-master/590/RMM_COMPONENT_TO_TEST_NAME=pxp_agent,SLAVE_LABEL=beaker,TEST_TARGET=osx1012-64a/console

Revert "(PA-2219) Add support for Fedora 30"

---

acceptance/tests/multiple_pxp_agent_daemon.rb
acceptance/tests/pxp-module-puppet/run_puppet_umask.rb

Previous to this commit, two tests: run_puppet_umask and
multiple_pxp_agent_daemon were attempting to use the 'service' command to check
for systemd. This will not work for newer fedora versions since sysvinit was
removed and the 'service' command went with it.
Thus we check if the file that /proc/1/exe points to is systemd
Merging this to 1.9.x also, as we need it for puppet-agent 5.5.x.

(PA-2267) Update pxp tests to check /proc/1/exe for systemd (1.9.x)

---

.gitignore
lib/CMakeLists.txt
lib/inc/pxp-agent/module_cache_dir.hpp
lib/inc/pxp-agent/modules/task.hpp
lib/inc/pxp-agent/request_processor.hpp
lib/inc/pxp-agent/util/bolt_helpers.hpp
lib/inc/pxp-agent/util/bolt_module.hpp
lib/src/module_cache_dir.cc
lib/src/modules/task.cc
lib/src/request_processor.cc
lib/src/util/bolt_helpers.cc
lib/tests/CMakeLists.txt
lib/tests/unit/module_cache_dir_test.cc
lib/tests/unit/modules/task_test.cc

This commit adds a new class, ModuleCacheDir, which will provide methods for
creating and purging cache dirs. A single ModuleCacheDir object will be shared
between all pxp bolt modules.
The shared object allows bolt modules to share the same mutex for creating and
purging the cache dirs.

(PCP-868) Add ModuleCacheDir class to control cache dirs

---

ext/solaris/smf/pxp-agent.xml

Prior to this commit, the `refresh` action was executed by SMF when the package manifest changed. However, no action was implemented for `refresh`, hence the pxp-agent service did not automatically restart
when the puppet-agent package was upgraded.
This commit adds functionality to the `refresh` action, killing the service for it to be restarted automatically by SMF, which is the intended behavior.

(PE-26709) Restart Solaris 11 pxp-agent service on package upgrade

---

acceptance/lib/pxp-agent/bolt_pxp_module_helper.rb
acceptance/tests/pxp_module_bolt_download_file/download_file.rb
lib/inc/pxp-agent/modules/download_file.hpp
lib/inc/pxp-agent/util/bolt_helpers.hpp
lib/src/modules/download_file.cc
lib/src/util/bolt_helpers.cc
lib/tests/unit/modules/download_file_test.cc

This work should expand the download_file module in pxp-agent to implement taking an array of files/directories/symlinks and creating them all on the system.
The schema for download_file already takes an array (previously it just operated on the first element), so the only update required for the schema is a field to differentiate between files/dirs/symlinks.

(PCP-874) Add functionality for recursive downloads in download_file

---

.gitignore
acceptance/lib/pxp-agent/bolt_pxp_module_helper.rb
acceptance/tests/pxp_module_bolt_script/run_script.rb
lib/CMakeLists.txt
lib/inc/pxp-agent/modules/script.hpp
lib/inc/pxp-agent/modules/task.hpp
lib/inc/pxp-agent/util/bolt_helpers.hpp
lib/src/modules/command.cc
lib/src/modules/script.cc
lib/src/modules/task.cc
lib/src/request_processor.cc
lib/src/util/bolt_helpers.cc
lib/tests/CMakeLists.txt
lib/tests/resources/scripts_cache/3D57FCC5FBDC53E667D16493D38621F36B2CF7DB244986B07A4FBCFECE9E19BD/test script.ps1
lib/tests/resources/scripts_cache/3D57FCC5FBDC53E667D16493D38621F36B2CF7DB244986B07A4FBCFECE9E19BD/test_script.ps1
lib/tests/resources/scripts_cache/71A2725F36221AAE75AF076D01D18744DA461A02DD2AB746447BC41C71248562/test_script.sh
lib/tests/unit/modules/download_file_test.cc
lib/tests/unit/modules/script_test.cc
lib/tests/unit/modules/task_test.cc

This PR adds a new module to pxp-agent: script. The script module will take a PCP message with script file information and any arguments to send. After receiving the message the pxp-agent will download and execute the script with any provided arguments.

(PCP-869) Add script module to pxp-agent

---

acceptance/lib/pxp-agent/test_helper.rb

Due to FIPS enablement work in Lovejoy, how we handle the bouncycastle
dependency has changed. This necessitated some tweaks to the
pcp-broker development profiles.

(maint) Change lein profile for pcp-broker in acceptance

---

acceptance/files/complex-args.json
acceptance/files/complex-output
acceptance/files/complex-task.ps1
exe/PowershellShim-Helper.ps1

Previously, when parsing xml in the `Get-ContentAsJson` implementation a regex used to filter out xml elements with whos `MemberType` `Properties` had a name that was preceeded with `__` or contained the string `type`. Filtering on the string `type` caused task parameters that contain that string to be ignored, preventing users from being able to effectively pass powershell task paramters with the `type` in the name. Unfortunately, with the current implementation powershell parameters with the name `type` will be clobbered by a `Property` called type. However this commit updates the regex to *only* filter out the property that exactly matches `type`. Note that this work allows powershell task parameters with `type` in the name, but not the name `type` and only affects powershell <= 2.

(PCP-883) Allow powershell task parameters with `type` in the name

---

acceptance/tests/pxp_module_bolt_command/run_command.rb
lib/src/modules/command.cc
lib/tests/unit/modules/command_test.cc

This commit updates the "run" action in the command pxp-agent module to wrap
all commands to run in a shell. This feature mistakenly assumed that bolt
commands ran with no shell, when that's not the case, thus we need to change
the implementation to wrap everything in a shell.
This commit wraps everything in a shell by creating the command structure with
the shell as the command to execute in leatherman. Then the arguments will
include the actual command passed from the PCP message.
For windows:
Bolt uses WinRM, which defaults to powershell as the shell (and that isn't
believed to be configurable) so we default to powershell.exe
For Posix systems:
We use the posix defined getpwuid (https://linux.die.net/man/3/getpwuid) to
find the default shell for the calling pxp-agent processes user.

(PCP-844) Update the command module to use a shell

---

ext/suse/pxp-agent.init

In the current state, SLES boxes that has more than one PXP agent process running at a time will cause a syntax error on the pxp-agent init script. In the correct manner, and what happens when only one pxp-agent process is running, the bash tests in the script behave like so:
```
[ x -eq y ]
```
However, in the event of more than one process, the tests in the script become this:
```
[ x -eq y z ]
```
which is syntactically incorrect, and causes control of the process through the system to fail due to the bad syntax. What I am proposing is to loop over the results of the same `pgrep` command already being used, matching the PID that is in the PID file, and killing the extraneous one(s). I have tested this on several SLES boxes in my enterprise that were impacted by this, and each of them …

(PCP-889) Fixing syntax error when more than one pxp-agent process is running

---

.gitignore
Boltdir/site-modules/pxp_dev/lib/puppet/functions/pxp_root.rb
Boltdir/site-modules/pxp_dev/lib/puppet/functions/replace_inventory.rb
Boltdir/site-modules/pxp_dev/plans/build.pp
Boltdir/site-modules/pxp_dev/plans/rebuild.pp
Boltdir/site-modules/pxp_dev/plans/upload_to_agent.pp
Boltdir/site-modules/pxp_dev/tasks/build_deps_with_vanagon.json
Boltdir/site-modules/pxp_dev/tasks/build_deps_with_vanagon.rb
Boltdir/site-modules/pxp_dev/tasks/run_pxp_make.json
Boltdir/site-modules/pxp_dev/tasks/run_pxp_make.sh
Boltdir/site-modules/pxp_dev/tasks/upload_from_builder_to_agent.sh
Boltdir/site-modules/pxp_dev/tasks/upload_from_builder_to_agents.json

This commit adds a new Boltdir and two plans for building and rebuilding
pxp-agent. Both plans take a host as input where an agent is installed,
and will update the host's pxp-agent binary (and pxp-agent modules dir)
with changes built using the files currently in the local checkout of
pxp-agent.
The plans to use are:
* pxp_dev::build
* pxp_dev::rebuild

(maint) Add bolt plans for building/rebuild pxp-agent

---

acceptance/tests/pxp-module-puppet/run_puppet_twice.rb

With the addition of https://github.com/puppetlabs/puppet/commit/939ab7ee958e82974f199f84ccb2d2bd1b2c72fc we need to wait a bit longer in the run_puppet_twice test.

(maint) Increase time/attempts for waiting for concurrent puppet runs

---

lib/inc/pxp-agent/modules/apply.hpp
lib/src/modules/apply.cc
lib/src/request_processor.cc
lib/tests/unit/modules/apply_test.cc

The `Apply` module does not need to use the curl client to download anything from master/puppetserver. this commit removes the client and it's configuration params.

(maint) Remove unused Apply constructor params

---

acceptance/files/modules/basic/files/data
acceptance/tests/pxp_module_bolt_apply/apply_catalog.rb
lib/src/modules/apply.cc

This commit allows the apply module to fetch files served by puppetserver/master needed during catalog application. This is achieved by no longer throwing away the puppetserver connection information used for pluginsync and no longer overriding the default file terminus.

(PE-29150) No longer isolate from puppetserver for application in apply module

---

Boltdir/site-modules/pxp_dev/plans/build.pp
Boltdir/site-modules/pxp_dev/tasks/build_deps_with_vanagon.rb

This commit updates the dev build plan to include an optional no_bundler
parameter that will ignore use of bundler when attempting the agent build

(maint) Allow plan for dev build to not use bundler

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/validate_file_paths.rb

https://github.com/puppetlabs/puppet-agent/pull/1912 changed the naming of nssm, causing 2 tests to fail.
Update the expected file path of nssm, and make the get_process_pids grep more strict.

(maint) Fix tests after nssm name change - master

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/validate_file_paths.rb

https://github.com/puppetlabs/puppet-agent/pull/1912 changed the naming of nssm, causing 2 tests to fail.
Update the expected file path of nssm, and make the get_process_pids grep more strict.

(maint) Fix tests after nssm name change - 1.9.x

---

acceptance/Gemfile

This commit updates the pcp-client gem requirement to take up new changes in the pcp-client gemspec that pin dependencies to compatible versions.

(PE-29831) Update pcp-client ruby gem

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/tests/pxp_module_bolt_command/run_command.rb

This commit updates the max-message-size test and the test utils in the
following ways:
1. The test itself is updated to change execution such that a large file is
created using beaker, rather than generated as part of the command execution.
Then the command that's actually run just echos that file.
2. The test utils have been updated such that the timeout for pcp operations
is 6 minutes instead of 1. We don't expect the command to take all 6 minutes,
but the test was failing because the output takes at least 1 minute to
process.

(PE-28827) Update max-message-size test with fixes

---

acceptance/tests/pxp_module_bolt_command/run_command.rb
lib/src/configuration.cc
lib/tests/common/mock_connector.hpp

This commit updates the max-message-size to be 64*1024*1024 rather than
64*1012*1012 in order to more accurately calculate the number of bytes
in 64 megabytes.

(maint) Update max-message-size calculation

---

acceptance/lib/pxp-agent/test_helper.rb
modules/pxp-module-puppet.bat

https://github.com/puppetlabs/puppet-agent/pull/1973 removes `INSTALLDIR\puppet\bin`
form PATH on Windows. This commit updates
pxp-module-puppet to use the full path to Ruby
The puppet process will run like:
`"C:\Program Files\Puppet Labs\Puppet\puppet\bin\ruby.exe" -S -- "C:\Program Files\Puppet Labs\Puppet\puppet\bin\puppet" agent`

(PCP-902) use Ruby from Puppet bin

---

acceptance/lib/pxp-agent/test_helper.rb
modules/pxp-module-puppet.bat

Reverts puppetlabs/pxp-agent#821
We will not change the PATH on puppet-agent so there is no need for this change

Revert "(PCP-902) use Ruby from Puppet bin"

---

acceptance/tests/crl_revocation.rb

The `cp -r` command does not follow symlinks. So the command to copy the ssl
directory to `/tmp/ssl-bkp` results in a new symlink being created
`/tmp/ssl-bkp/ca` that points to `/etc/puppetlabs/puppetserver/ca`.
So later the test tries to copy the backup to the destination:
cp /tmp/ssl-bkp/ca/ca_crl.pem /etc/puppetlabs/puppet/ssl/ca/ca_crl.pem
and it fails because the source and destination files are actually the same
file (inode).
Instead use `cp -rL` which follows symlinks. As a result of the change, the
backup directory contains a copy of the ca directory after following symlinks.

(maint) Use cp -rL when backing up ca directory

---

ext/osx/pxp-agent.newsyslog.conf

OS X uses newsyslog to rotate log files. By default it's configured to
run every 30 minutes. Add a configuration file for the pxp-agent log
file, similar to the logrotate one.
The configuration file does the following:
- rotate logs every day
- keep a maximum of 30 files
- send SIGUSR2 to pxp-agent after rotating
- don't write specific headers when rotating (may interfere with
external log analysis tools)

(PA-3491) Add newsyslog config for pxp-agent

---

ext/pxp-agent.logrotate
ext/systemd/pxp-agent.logrotate

When the logs are rotated, gzip can throw the error
`gzip: stdin: file size changed while zipping`.
This happends if new logs are added to the file when the same file
is gzipped.
Adding delaycompress to logrotate configurations postpones compression
of the previous log file to the next rotation cycle, so that the
compression will not happen to the current log file.

(PCP-850) Add delaycompress to logrotate settings

---

appveyor.yml
lib/src/modules/task.cc
lib/tests/unit/modules/task_test.cc

The default input method is already `both` (when there is no entry for input_method). This commit adds support for explicitly specifying `both` in task metadata.

(PE-30708) Support `both` as valid task input method

---

CMakeLists.txt
lib/inc/pxp-agent/configuration.hpp
lib/src/configuration.cc

This is mostly for AIX where we have to log through its syslog daemon in
order to benefit from log rotation.
To enable logging to syslog, the user needs to specify "syslog" as the
value for the "logfile" option.

(PA-3490) Add syslog logging to pxp-agent

---

appveyor.yml
lib/src/modules/task.cc
lib/tests/unit/modules/task_test.cc

* commit '40a666c4a7b5cea133892a3be6f24b51e164f791':
(maint) Pin back pester version
(PE-30708) Support `both` as valid task input method
(packaging) Bump to version '1.9.15' [no-promote]
* lib/tests/unit/modules/task_test.cc - manually adapted
Conflicts:
* CMakeLists.txt - keep main version
* appveyor.yml - pin pester version
* lib/src/modules/task.cc - manually solved conflicts

(maint) Merge 1.9.x to master

---

lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/modules/apply.hpp
lib/inc/pxp-agent/modules/task.hpp
lib/src/configuration.cc
lib/src/modules/apply.cc
lib/src/modules/task.cc
lib/src/request_processor.cc
lib/tests/resources/config/bad-master.conf
lib/tests/resources/config/multi-broker-both-uris.conf
lib/tests/resources/config/multi-broker-master-uris.conf
lib/tests/unit/configuration_test.cc

This commit updates pxp-agent as part of the work to deprecate the
`master_uris` parameter. As of this commit, using `master_uris` should
still work, but using the new `primary_uris` should also now work.
pxp-agent will now look for both of those config values when setting
that param.

(PE-30624) Deprecate master_uris, add primary_uris

---

lib/src/modules/apply.cc

This ensures that spurious messages of the form 'Local environment..
doesn't match...' are not printed when the apply ruby shim is executed
and the passed-in environment is different from production.
Signed-off-by: Enis Inan <enis.inan@puppet.com>

(PE-31415) Set apply ruby shim environment to passed-in environment

---

exe/CMakeLists.txt
exe/apply_ruby_shim.rb
lib/inc/pxp-agent/modules/apply.hpp
lib/inc/pxp-agent/modules/file.hpp
lib/inc/pxp-agent/modules/script.hpp
lib/inc/pxp-agent/modules/task.hpp
lib/src/modules/apply.cc
lib/src/modules/task.cc

Previously, this shim existed only as a hardcoded Ruby string in a C++ 
source file. That file would be written when needed and purged after a 
period of disuse. But changes to the content weren't necessarily picked up,
as it would only be rewritten after being purged for inactivity. That led
to a problem where pxp-agent installations which had been upgraded would
fail to run apply/apply_prep, because they had an old copy of the shim. The
old version expected to receive a master_uris argument but pxp-agent had
been updated to pass primary_uris instead.
We now manage this file as a regular file and include it during the 
build/packaging process so that it will be automatically upgraded by the 
package manager.

(PE-31871) Extract apply shim to a file

---

lib/src/util/bolt_module.cc
lib/src/util/utf8.cc
lib/tests/resources/tasks-cache/b26e34bc50c88ca5ee2bfcbcaff5c23b0124db9479e66390539f2715b675b7e7/null_byte
lib/tests/unit/modules/task_test.cc

Previously, pxp-agent would accept task output containing null bytes and
would return it to orchestrator. This caused a database error as null
bytes cannot be written to postgres. These null bytes are also not
allowed by the task spec, so this behavior was incorrect.
The root issue is that the isValidUTF8 helper, which uses rapidjson to
validate each character, considers null bytes to be valid. Technically
this isn't wrong, as the null character is a UTF-8 character, but it's
not a valid character in a null-terminated string.
We now supplement the regular validity check with an additional check
that the string doesn't contain any null bytes.
This also fixes a bug where we could return a result containing invalid
UTF-8 in the case where both stdout and stderr had invalid UTF-8 output.
We …

(PE-31216) Disallow null bytes in task output

---

ext/osx/pxp-agent.plist
ext/solaris/smf/pxp-agent.xml

This was something we forgot to do as part of PA-437. Note that we only
do this for Solaris and OSX to be consistent with how things are
currently done for Puppet.
Signed-off-by: Enis Inan <enis.inan@puppet.com>

(PCP-890) Update Solaris and OSX service scripts to use wrapper script

---

acceptance/lib/pxp-agent/test_helper.rb
acceptance/setup/common/050_Setup_Broker.rb

Add the 'jdk.tls.ephemeralDHKeySize=2048' JVM option when running pcp-broker, as the default DH key size is too small for openssl 1.1.1k FIPS.

(PA-3974) Increase DH key size for pcp-broker

---

.travis.yml
appveyor.yml
lib/inc/pxp-agent/configuration.hpp
lib/inc/pxp-agent/pxp_connector_v1.hpp
lib/inc/pxp-agent/pxp_connector_v2.hpp
lib/src/agent.cc
lib/src/configuration.cc
lib/src/pxp_connector_v1.cc
lib/src/pxp_connector_v2.cc
lib/tests/common/mock_connector.hpp
lib/tests/unit/action_request_test.cc
lib/tests/unit/agent_test.cc
lib/tests/unit/pxp_connector_v1_test.cc
lib/tests/unit/pxp_connector_v2_test.cc

We now pass the log level and stream through to the cpp-pcp-client
Connector classes which in turn use them to configure logging on the
websocketpp connection. This entails storing the parsed log level on the
Configuration::Agent object and providing a method to retrieve the log
stream object.
This depends on https://github.com/puppetlabs/cpp-pcp-client/pull/257

(PCP-906) Configure WebSocket++ loggers

---

acceptance/setup/common/050_Setup_Broker.rb

If a VM doesn't have make installed then Lein will fail to build. Historically our EL platforms
had make installed my default, but the new GCE images we'll be switching to does not have it installed.

(PA-4487) Add make in the pre-suite

---

acceptance/lib/pxp-agent/test_helper.rb

Prior to this commit, the `create_sleep_manifest` method generated a Puppet manifest reliant on the legacy fact `$osfamily`, causing tests to fail in Puppet 8.
This commit updates that fact with the modern structured `$facts['os']['family']`.

(PA-4905) Updates legacy facts in test

---

acceptance/setup/common/050_Setup_Broker.rb

The move to trapperkeeper-webserver-jetty10 is incompatible with jdk8. Since main branch of pxp agent is promoted into both 7.x and main branch (which has tkw10) of agent and update to jdk11 is required.

(PE-37243) update acceptance test java version to jdk11

---

acceptance/setup/common/050_Setup_Broker.rb

In a previous commit [1], the jdk version used in the acceptance tests was updated to v11 and the version of lein that the test was using (2.7.1) incompatible with jdk11. This commit updates to the version of lein that runs elsewhere in CI.
[1]: 9db00cfee8c019f6a7590d76dbdc46886f760f4a

(PE-37243) update lein to v2.9.0

---

lib/inc/pxp-agent/pxp_connector.hpp

int32_t type def is optional in C++11, some vendors ship gcc suite with them automatically included, some don't.
observed `'uint32_t' does not name a type` with gcc 13, which will ship with Ubuntu 24.
https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

(maint) ensure int32_t type defined

---

acceptance/tests/crl_revocation.rb

We are encountering an issue with tests running on AIX due to incorrect system time. While we are waiting on a permanent fix in ITHELP-99479, this temporary workaround sets the timesync property on the Beaker host object to "true" if the host is AIX.

(PA-7090) Correct system time on AIX
