lib/src/configuration.cc
Here if set the default path for the modules dir: on *nix we use the
location on the /opt/.. tree specified in Puppet Specs; for Windows we
use the relative path of the pxp-agent.exe executable.
=> (PCP-57) Determine default path for modules dir

lib/src/configuration.cc
Previously logging from cpp-pcp-client would not be configured
when statically linking Boost.Log. Use the new setupLogging util
in cpp-pcp-client to configure logging when configuring for
pxp-agent.
=> (PCP-68) Fix logging for cpp-pcp-client

exe/main.cc, lib/src/configuration.cc, lib/src/modules/status.cc
Fix UTF-8 logging and argument handling.
=> (PCP-70) Fix up unicode handling

ext/pxp-agent.logrotate
This commit adds a logrotate config for the pxp-agent.
=> (PCP-92) Add logrotate configuration

lib/tests/unit/configuration_test.cc, lib/tests/unit/modules/status_test.cc, lib/tests/unit/util/posix/pid_file_test.cc
- Creating and removing directories as requested for each unit test, as
after PCP-77 pxp-agent does not create directories anymore;
- ensuring that Configuration is initialized for each unit test.
=> (PCP-105) Fix unit tests

vendor/cpp-pcp-client.cmake
Updating cpp-pcp-client_LIBRARY suffix to .a in cpp-pcp-client.cmake
=> (maint) Update cpp-pcp-client submodule to 7e20507

exe/CMakeLists.txt, lib/CMakeLists.txt, lib/tests/CMakeLists.txt
pxp-agent always created a static libpxp-agent, so clarify that.
=> (PCP-136) Update for cpp-pcp-client using dynamic linking

exe/main.cc, lib/src/action_request.cc, lib/src/external_module.cc, lib/src/request_processor.cc, lib/src/thread_container.cc, lib/src/util/posix/daemonize.cc
Rewording messages. Avoiding logging at INFO with too much information.
Logging the content of requests at TRACE.
=> (PCP-5) Improve log messages

lib/src/configuration.cc
During configuration validation we now ensure that the spool directory
is writable.
=> (PCP-154) Ensure that the spool dir is writable

acceptance/tests/invalid_ssl_config.rb
The acceptance test for invalid SSL config depends on a grep statement returning 0.
If this fails, we only see that grep failed; without seeing the text it was grepping.
This commit catches grep failing then fails on an exception that will compare the expected log entry with the actual log contents.
=> (maint) Improve output if SSL config test fails

README.md, exe/main.cc, lib/src/configuration.cc, modules/README.md
=> (PCP-218) Fix --connection-timeout docs

README.md
Using names instead of numbers.
[skip ci]
=> (maint) Update reference tags in README

acceptance/Gemfile, acceptance/lib/pxp-agent/test_helper.rb, acceptance/tests/pxp-module-puppet/run_puppet.rb
2nd PR for this test case; contains squashed commits of fixes made in response to first PR  https://github.com/puppetlabs/pxp-agent/pull/295
=> (PCP-188) Acceptance test of pxp-module-puppet run

lib/inc/pxp-agent/action_request.hpp, lib/inc/pxp-agent/request_processor.hpp, lib/src/action_request.cc, lib/src/request_processor.cc, lib/tests/unit/action_request_test.cc
- adding results_dir_ to ActionRequest;
- tidying up RequestProcessor and ResultsStorage.
=> (maint) Improve usage of ActionRequest in RequestProcessor

modules/README.md
We're simplifying the interface for external modules by requiring that
the output must be written only to file in case the `output_files`
entry is included in the action input.
This change implies that pxp-agent will need to read the outcom of the
action run from file.
On the other hand, modules will have a simpler output requirement, as
they won't need to guarantee the same output on files and stream.
[skip ci]
=> (PCP-207) Ext modules interface: rely only on files

acceptance/setup/aio/pre-suite/010_Install.rb, acceptance/setup/common/010_Setup_Broker.rb, acceptance/tests/pxp_agent_version.rb
PR #261 had numerous improvements to the acceptance code; but most of the changes were implemented incidentally or became n/a.
This PR brings in the last couple of improvements that were proposed in PR 261
=> (PCP-235) Bring in the remainder of Ethan's acceptance improvements

lib/tests/resources/broken_modules/reverse_bad_json_format, lib/tests/resources/broken_modules/reverse_bad_json_format.bat, lib/tests/resources/broken_modules/reverse_no_metadata, lib/tests/resources/broken_modules/reverse_no_metadata.bat, lib/tests/resources/modules/convert_test, lib/tests/resources/modules/convert_test.bat, lib/tests/unit/external_module_test.cc
Add tests covering validation of module metadata as well as action output.
=> (PCP-239) add more module interaction tests

README.md
Using same style as cpp-pcp-client's README.
[skip ci]
=> (PCP-244) Style changes to README.md

modules/pxp-module-puppet, modules/pxp-module-puppet.md, modules/spec/unit/modules/puppet_spec.rb
This reverts commit 8575ffc30771a02733af8b5259b31cd0ca7f7981, reversing
changes made to e7093c69733ad12d8b0c7d1dac49cf20f8aa266e.
=> Revert "Merge pull request #329 from mruzicka/PCP-206_update_module_result_structure"

lib/src/configuration.cc
Solaris cleans up /var/run at reboot. Daemonization relies on the
existence of the PID file directory. Here we create such directory when
running on Solaris, if necessary.
=> (PCP-297) On POSIX, create /var/run/puppetlabs if needed

lib/src/action_response.cc
With the changes introduced for PCP-208 we modified the behaviour of the
status query action, by setting the "status" of a completed action in
relation to the validation of the output on stdout.
Here we restore the old behaviour that consists of setting the "status"
in relation to the exitcode value.
The reason for restoring the old  behaviour is that we want to preserve
compatibility against old versions of clj-pxp-puppet.
=> (maint) Restore previous behaviour of 'status query'

CHANGELOG.md
=> (maint) Prepare to release 1.1.0

acceptance/tests/pxp-module-puppet/run_puppet_agent_disabled.rb
=> (PCP-225) Acceptance test for attempting puppet run on a disabled agent

acceptance/tests/restart_host_run_puppet.rb
=> (PCP-232) Acceptance - ensure pxp-agent is usable after restarting host

acceptance/tests/restart_host_run_puppet.rb
QENG-3629 is an issue with accessing our AIX hosts following a restart.
Until that ticket is fixed, we need to skip the acceptance test that restarts the host, for AIX agents.
[skip ci]
=> (PCP-363) Skip test that restarts host for AIX agents

acceptance/lib/pxp-agent/test_helper.rb, acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb
PR #399 was accidentally pointed at master. The changes are needed on both branches. This commit merges the new test (and test helper code) to stable.
[skip ci]
=> (PCP-230) Merge new acceptance test from master to stable

acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb, acceptance/tests/pxp_agent_version.rb
Two commits, each fixing an acceptance test so it will pass on Cisco Nexus
[skip ci]
=> (PCP-514) Fix acceptance tests on Cisco Nexus

acceptance/lib/pxp-agent/config_helper.rb, acceptance/lib/pxp-agent/test_helper.rb, acceptance/tests/failover/intentional_shutdown_failover.rb, acceptance/tests/failover/timeout_failover.rb, acceptance/tests/invalid_ssl_config.rb, acceptance/tests/reconnect_after_broker_unavailable.rb
=> (PCP-457) Acceptance: Automate pxp-agent broker timeout failover test

acceptance/setup/common/035_StartPuppetServer.rb, acceptance/tests/failover/intentional_shutdown_failover.rb, acceptance/tests/failover/timeout_failover.rb, acceptance/tests/invalid_ssl_config.rb, acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb, acceptance/tests/reconnect_after_broker_unavailable.rb
Also ensure puppetserver runs after host restart.
=> (PCP-286) Retry `rm -rf` when it fails

acceptance/tests/service_stop_start.rb
PCP-286 had occasional failures in acceptance CI on Windows.
They were caused by tests/service_stop_start.rb leaving the service in the Paused state.
This commit updates the teardown block of tests/service_stop_start.rb to make sure the pxp-agent is in a working running state.
PUP-6702 means that the teardown needs to directly use the 'net' command on Windows rather than puppet managing the service state.
[skip-ci]
=> (PCP-286) Ensure service is running in service test teardown

acceptance/lib/pxp-agent/test_helper.rb, acceptance/tests/pxp-module-puppet/restart_pxp_agent_during_non_blocking_run.rb, acceptance/tests/pxp-module-puppet/run_puppet_during_puppet.rb, acceptance/tests/pxp-module-puppet/run_puppet_killed_puppet.rb, acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
Some changes to acceptance testing were committed straight to master. This PR cherry-picks them back to stable.
[skip ci]
=> (maint) Merge acceptance changes from master back to stable

CHANGELOG.md
Also fill in CHANGELOG for 1.2.2 release.
=> (doc) Update CHANGELOG for 1.3.0 release

MAINTAINERS
=> (maint) Update maintainers file

acceptance/tests/pxp-module-puppet/run_puppet_twice.rb
This test fails in CI when it requires either 1 or 2 puppet agent processes to be running but discovers 3.
1 instance is from puppet running as a service (despite the pre-suite stopping this).
Another instance is from puppet agent being used for another purpose (puppet agent --configprint).
This commit updates the test to not fail immediately on finding 3 pids and also adds a workaround in shutting down puppet at the start of the test.
[skip ci]
=> (PCP-632) Fix run_puppet_twice.rb on OSX

acceptance/lib/pxp-agent/test_helper.rb
Handles pxp-agent returning unknown status. This is currently considered
normal operation when an action has been queued but has not yet invoked
a process.
=> (PCP-657) Allow unknown status in acceptance tests

README.md
Updates the README to include the new `pcp-version` option.
=> (docs) Add pcp-version to README

acceptance/tests/pxp-module-puppet/run_puppet_nonASCII.rb
PUP-5756 should fix an issue in Puppet with UTF-8 characters in some
locales when writing to event log. Until that's fixed, skip the test.
=> (maint) Skip nonASCII test on japanese windows machines

CHANGELOG.md, CMakeLists.txt, locales/pxp-agent.pot
=> (packaging) Prepare 1.5.0 release

CHANGELOG.md, CMakeLists.txt, locales/pxp-agent.pot
=> (packaging) Prepare 1.5.1 release

CHANGELOG.md, CMakeLists.txt, locales/pxp-agent.pot
Reverts puppetlabs/pxp-agent#579
Targeted at wrong branch
=> Revert "(packaging) Prepare for 1.5.2 release"

CHANGELOG.md, CMakeLists.txt, locales/pxp-agent.pot
Round 2, now targeted at stable.
=> (packaging) Prepare for 1.5.2 release

modules/pxp-module-puppet, modules/spec/unit/modules/puppet_spec.rb
UPDATE WITH details of what ticket triggered this for the inspect
removal
@Magisus can you add some more info for the commit message?
I'm going to assume there was discussion elsewhere about "breaking" the report format.
=> (PCP-751) Remove kind from pxp-module-puppet

acceptance/Rakefile, acceptance/setup/common/050_Setup_Broker.rb
=> (maint) Update testing to use pcp-broker 1.4.0

.travis.yml, .travis_target.sh, appveyor.yml
Updates the appveyor config to use maintained packages hosted on
myget.org.
=> (maint) Update appveyor config to use maintained packages

lib/src/modules/task.cc, lib/tests/unit/modules/task_test.cc, locales/pxp-agent.pot
WIP, this is an initial skeleton. I left some TODOs there for a few questions I have about the behavior.
=> (PCP-773) Implement client-side failover for task downloads

exe/CMakeLists.txt, lib/src/modules/task.cc
Update to support both rapidjson 1.0.2 and 1.1.0.
=> (maint) Prepare for rapidjson 1.1.0

lib/tests/unit/configuration_test.cc
Compute the argument count (`argc`) value from the size of the `argv` array instead of hardcoding it.
=> (maint) Compute argument count

acceptance/tests/pxp-module-puppet/run_puppet_agent_non_root.rb
Please let this be the last fix 🙏
=> (PCP-792) fix test on osx

CHANGELOG.md, CMakeLists.txt, locales/pxp-agent.pot
Do 1.5.x merge and prepare 1.8.1 release.
=> (packaging) Prepare 1.8.1 release

CMakeLists.txt, locales/pxp-agent.pot
This a preparatory version bump in advance of the puppet agent 5.5.0 release.
=> (packaging) Update reported version to 1.9.0

lib/inc/pxp-agent/configuration.hpp, lib/inc/pxp-agent/modules/task.hpp, lib/src/configuration.cc, lib/src/modules/task.cc, lib/src/request_processor.cc, lib/tests/common/mock_connector.hpp, lib/tests/unit/agent_test.cc, lib/tests/unit/configuration_test.cc, lib/tests/unit/modules/task_test.cc, locales/pxp-agent.pot
Configure task download timeouts based on new options `task-download-connect-timeout` and `task-download-timeout`.
=> (PCP-797) Add task-download-connect-timeout, task-download-timeout

acceptance/.beaker.yml
Analogous to puppetlabs/puppet-agent#1470
=> (maint) Update internal test forge URI

lib/src/modules/task.cc, lib/tests/unit/modules/task_test.cc, locales/pxp-agent.pot
Add the shell feature on non-Windows hosts, and add the powershell
feature if a powershell executable is found.
=> (PCP-836) Add powershell and shell features

acceptance/tests/invalid_ssl_config.rb
Re-enable the `invalid_ssl_config` test, and update it to use the new
`puppetserver ca` command to generate a CA and certs. Uses only
`puppetserver ca setup` because other commands require a running CA
service.
=> (PCP-856) Update invalid_ssl_config to use new ca command

acceptance/tests/proxy_connection.rb, acceptance/tests/tasks/run_echo.rb, acceptance/tests/tasks/run_ps1.rb, acceptance/tests/tasks/task_purged_from_cache.rb
Reverts puppetlabs/pxp-agent#719.
=> Revert "(maint) Fix tests that only worked when agents are all windows or not"

acceptance/lib/pxp-agent/bolt_pxp_module_helper.rb, acceptance/tests/pxp_module_bolt_command/run_command.rb, exe/CMakeLists.txt, exe/execution_wrapper.cc, exe/tests/main.cc, lib/CMakeLists.txt, lib/inc/pxp-agent/modules/command.hpp, lib/inc/pxp-agent/util/bolt_module.hpp, lib/src/configuration.cc, lib/src/external_module.cc, lib/src/modules/command.cc, lib/src/modules/task.cc, lib/src/request_processor.cc, lib/src/util/bolt_module.cc, lib/tests/CMakeLists.txt, lib/tests/unit/modules/command_test.cc
Supports 'command run' for bolt over PCP. See individual commit messages.
=> (PCP-867) Implement run_command over PCP for bolt support

.gitignore, acceptance/lib/pxp-agent/bolt_pxp_module_helper.rb, acceptance/tests/proxy_connection.rb, acceptance/tests/pxp_module_bolt_download_file/download_file.rb, acceptance/tests/pxp_module_bolt_task/run_echo.rb, acceptance/tests/pxp_module_bolt_task/run_multifile.rb, acceptance/tests/pxp_module_bolt_task/run_ps1.rb, acceptance/tests/pxp_module_bolt_task/run_puppet.rb, acceptance/tests/pxp_module_bolt_task/run_ruby.rb, acceptance/tests/pxp_module_bolt_task/task_download.rb, acceptance/tests/pxp_module_bolt_task/task_implementations.rb, acceptance/tests/pxp_module_bolt_task/task_purged_from_cache.rb, lib/CMakeLists.txt, lib/inc/pxp-agent/modules/download_file.hpp, lib/src/modules/download_file.cc, lib/src/request_processor.cc, lib/tests/CMakeLists.txt, lib/tests/resources/download_files/file.txt, lib/tests/unit/modules/download_file_test.cc
This commit adds a new boltmodule child: DownloadFile. This pxp module simply                                                                                                                                                                                                                                                                                           downloads a file and returns, with no calls to external processes.        
Since DownloadFile does not need external processes: the class implements its'                                                                                                                                                                                                                                                                                          own …
=> (PCP-868) Add download_file module

acceptance/tests/pxp_module_bolt_script/run_script.rb, lib/src/modules/script.cc, lib/tests/unit/modules/script_test.cc
This matches Bolt.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (PCP-885) Change args to array of strings in run_script

lib/src/util/bolt_helpers.cc
This commit updates the download helpers to catch the EXDEV error code
during boost::filesystem::rename. This error occurs when rename is
called with a source and destination on different filesystems. In this
case, we can retry the file move by using copy and then remove rather
than rename.
=> (PCP-886) Catch EXDEV error on file rename, retry with copy

acceptance/Gemfile, acceptance/lib/pxp-agent/test_helper.rb, acceptance/setup/common/050_Setup_Broker.rb
- add beaker-gke as dependency for acceptance
- limit lein heap memory allocation on gke container
=> (PA-2981) add beaker-gke support

acceptance/tests/proxy_connection.rb, acceptance/tests/pxp_module_bolt_download_file/download_file.rb, acceptance/tests/pxp_module_bolt_script/run_script.rb, acceptance/tests/pxp_module_bolt_task/task_download.rb, acceptance/tests/pxp_module_bolt_task/task_implementations.rb, acceptance/tests/service_stop_start.rb
update asserts to handle alignment spacing in resource output
=> (maint) fix resource asserts alignment

acceptance/lib/pxp-agent/bolt_pxp_module_helper.rb, acceptance/tests/pxp_module_bolt_apply/apply_catalog.rb, lib/src/modules/apply.cc
WIP- this is the first cpp module with multiple actions. This first commit is just feeling out how to build up schema validation for that.
=> (PCP-894) Add `prep` action to `apply` module

lib/src/modules/apply.cc
This commit updates the pxp-agent `prep` action in the `apply` module to print the same facts as in Bolt's `apply_helpers::custom_facts` task.
=> (PCP-894) Update apply prep action to print same facts as bolt

lib/src/modules/apply.cc
Previously we looked up a default env for application. This caused report environemnt to not provide a value for environment name in apply report. By using remote environemnt everywhere we do not rely on default env.
=> (maint) Use remote env everywhere

acceptance/tests/crl_revocation.rb
This commit removes the master from the agent hosts used in the
`crl_revocation` test.  If the master is included in the test the
master's ssl cert will be revoked centrally causing SSL authentication
to fail.
=> (maint) Only run crl_revoke test on external agent

acceptance/Gemfile
Update Gemfile location_for to accept https git URLs
=> (maint) update Gemfile location_for

acceptance/lib/pxp-agent/test_helper.rb
Several tests rely on pxp-agent to start a process, and then later on, check for
the process and kill it. Prior to cygwin 3.0, the `ps -eW` command returned the
Windows pid in the PID column.
In Cygwin 3, the `ps` command returns the Cygwin pid and you must use `ps -elW` to
retrieve the Windows pid. From the release notes[1]
Cygwin PIDs have been decoupled from Windows PID. Cygwin PIDs are now
incrementally dealt in the range from 2 up to 65535, POSIX-like. Native
Windows processes not started by Cygwin processes are mapped into the range
beyond 65535.
In order to find/kill a process started outside of cygwin/bash, like when
pxp-agent starts ping, the test must retrieve the Windows PID and pass that to
taskkill.
This commit eliminates places where we were using `ps` to retrieve Windows …
=> (PA-4550) Use WMI to lookup windows pid

acceptance/Gemfile, acceptance/tests/multiple_pxp_agent_daemon.rb, acceptance/tests/pxp_module_bolt_apply/apply_catalog.rb, acceptance/tests/pxp_module_puppet/run_puppet_umask.rb
This PR updates deprecated Beaker methods used in tests and specifies the latest major version of beaker-hostgenerator in the Gemfile.
=> Acceptance test updates

lib/src/module_cache_dir.cc, locales/pxp-agent.pot
This retry loop with exponential backoff replaces a similar loop in leatherman.
I tested this and it works, I cleaned up the logging.
=> (PE-37481) Add retry loop to getCacheFile

lib/src/module_cache_dir.cc
In the original implementation of the retry logic (https://github.com/puppetlabs/pxp-agent/pull/852/files) a while loop using pointers was used to control max retries. On some platforms this approach resulted in broken pointers. Instead, use a for loop and return result of downloadFileFromMaster directly when it does not raise.
=> (PE-37481) Return result of downloadFileFromMaster directly on retry

acceptance/tests/crl_revocation.rb
This reverts commit bfde197b367bdf50db215c1a7367a8b7a3855279.
=> Revert "(PA-7090) Correct system time on AIX"
